### ISSUE TITLE
Why is it so slow?

### ISSUE THREAD

**Issue by BlasphemyAngels** [davidhalter/jedi#1008]
I have installed the jedi. But when I use the module "tensorflow", the auto-complete is so slow. Why is it?

**Comment by davidhalter** [comment]
Since I'm not sure what setup you're using and I have no idea what your problem might be - jedi is not something you can use directly. It's a library. Please create an issue in your plugin issue tracker. That makes way more sense, since the slowness might be caused by a lot of different reasons.

I doubt that it's jedi's fault that tensorflow completions are slow (also what is slow). People would have talked about it way sooner.
