### ISSUE TITLE
Python 3.5 Test Fails Itself

### ISSUE THREAD

**Issue by MohamedAlFahim** [davidhalter/jedi#1023]
> Could not find a version that satisfies the requirement tox-travis (from versions: )

@davidhalter It has troubles installing Tox. Fortunately, the other Python version builds for my Docstring fix pull request did not fail. #1021

**Comment by davidhalter** [comment]
The issue was actually nothing serious. It was a service (either PyPI or something inside travis) that didn't work properly:

`
 Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f22a12fc2e8>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/tox-travis/
`
I was not able to restart it, because the PR was merged. However the current build is passing (with your changes) so no worries - it wasn't a jedi issue.
