### ISSUE TITLE
Nvim Segfault

### ISSUE THREAD

**Issue by nsomaru** [davidhalter/jedi#1041]
Jedi causes a segfault under certain circumstances when using nvim. I can reproduce this issue, but some assistance with producing a bug report would be appreciated.

**Comment by davidhalter** [comment]
If you're on linux you could try using jedi's master branch. There it won't happen anymore, because the things that could cause a segfault are now part of a subprocess. The segfaults come from third-party libraries that are inspected. Please let me know if there is still a segfault issue with master (there are obviously other issues on master).

**Comment by nsomaru** [comment]
Debian stretch.

Installing jedi with vim-plug like so: 
`Plug 'davidhalter/jedi-vim', {'branch': 'master'}`
I still segfault which kills nvim. Obviously a no-go for development :(

Is there any further info required?

**Comment by davidhalter** [comment]
I'm pretty sure that the segfaults are part of the vim/python binding (because I've seen some before) or even Python itself. It's not like jedi does any crazy stuff and that there is a fix in jedi.

If you have a reproduction case I'm happy to post it to the Python or VIM tracker, but I don't see how I could do anything segfaults - since it's not a concept that is known in Python.

OH, now I realize: It's probably related to you only updating jedi-vim. That doesn't work. There will still be segfaults. If you upgrade jedi to master (note: not jedi-vim), then you should be fine - or let's say, at that point I cannot do anything anymore against segfaults.
