### ISSUE TITLE
[question] Custom parameter type inference

### ISSUE THREAD

**Issue by gatesn** [davidhalter/jedi#1049]
I see that Jedi can perform parameter type inference on docstrings and pep484, however I'm trying to add my own (for quite a custom use-case).

The use-case is that functions are wrapped in decorators, and based on the decorator we know the types of all parameters that will be passed to the function. Therefore I'd like to tell Jedi about these without requiring the types to be declared in docstrings. 

I've taken a stab at this by patching the `jedi.evaluate.param.ExecutedParam.infer` method and calling out to an additional source of hints. However I'm struggling to understand what "ContextSets" are and how to go about using them.

I'm able to correctly infer the fully qualified name of the type for each parameter, I just don't know how to turn the string "my.Type" into something Jedi is happy with.

**Comment by davidhalter** [comment]
ContextSets are basically not that complicated. A ContextSet is basically just a few contexts combined, i.e. the result of type inference. The question is really much more what a Context is. 

A Context is an object that can be used to represent all kind of Python objects. In your case I'm not really sure you have to create your own context. I'm pretty sure you're just dealing with Python objects. What you probably need to do is to write some logic that imports things in jedi (docstrings.py does similar things, I think).

Closing, because I think this answers the question. Glad to answer more.
