### ISSUE TITLE
Definition for namedtuple is wrong

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1060]
I've noticed that jedi-vim opens the current dir when trying to goto a namedtuple class.

The following tries to reproduce this, showing two issues:

```python
source = """
from collections import namedtuple

Foo = namedtuple('Foo', 'id timestamp gps_timestamp attributes')
Foo
"""

from jedi.api import Script

lines = source.split("\n")
d = Script(source, line=len(lines)-1, column=1).goto_definitions()
d1 = d[0]

print(d1)
print(d1.line)
print(d1.module_path)
print(d1.get_line_code())
assert d1.line == 4
```

Output:
```
<Definition class Foo>
5
…/vim/plugged/jedi-vim/pythonx/jedi
Traceback (most recent call last):
  File "t-namedtuple.py", line 16, in <module>
    print(d1.get_line_code())
  File "…/vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 381, in get_line_code
    lines = parser_cache[self._evaluator.grammar._hashed][path].lines
KeyError: '…/vim/plugged/jedi-vim/pythonx/jedi'
```

1. the line is expected to be 4, not 5?!
2. `get_line_code` should not crash?!
3. `module_path` is `…/vim/plugged/jedi-vim/pythonx/jedi`, which is the directory of the file, and the reason for jedi-vim to open it

Jedi master (144a1def).

**Comment by davidhalter** [comment]
It feels indeed strange. I have changed the get_line_code issue. It shouldn't be a problem anymore. The module_path is now None, which makes also more sense.

Since we're speaking about `goto_definitions`, this goes to the place where it's actually defined. This means in this case executed code from collections.namedtuple.

It doesn't make sense to move the "cursor" to the place where you define a namedtuple, because that's not generally what goto_definitions does. It's just a confusing name IMO that should be cleaned up. I'm probably going to name it `infer` in the future so that it's clear that it's about type inference and not a goto function.
