### ISSUE TITLE
Jedi import statement autocompletion removes working directory from sys.path

### ISSUE THREAD

**Issue by ju-w** [davidhalter/jedi#1148]
#### Paste the following code into an interactive python REPL:

```python
import jedi
import sys


source = 'import '
j = jedi.Interpreter(source, [locals()])

assert '' in sys.path
_ = j.completions()
assert '' in sys.path
```

In Jedi=0.12.0, the completion will remove the current directory (`''`) from sys.path. Jedi<0.12 will not exhibit this behaviour.

#### The code responsible can be found here:
https://github.com/davidhalter/jedi/blob/e96ebbe88f428775aa4dd16cbc9e7c3ee850e44d/jedi/api/project.py#L80-L93

#### A stacktrace inserted at that point will show:
<details><summary>Trace:</summary>

```
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\jedi\api\__init__.py", line 176, in completions
    completions = completion.completions()
  File "C:\Python36\lib\site-packages\jedi\api\completion.py", line 97, in completions
    completion_names = self._get_context_completions()
  File "C:\Python36\lib\site-packages\jedi\api\completion.py", line 197, in _get_context_completions
    only_modules=only_modules,
  File "C:\Python36\lib\site-packages\jedi\api\completion.py", line 275, in _get_importer_names
    retval = i.completion_names(self._evaluator, only_modules=only_modules)
  File "C:\Python36\lib\site-packages\jedi\evaluate\imports.py", line 461, in completion_names
    names += self._get_module_names()
  File "C:\Python36\lib\site-packages\jedi\evaluate\imports.py", line 398, in _get_module_names
    search_path = self.sys_path_with_modifications()
  File "C:\Python36\lib\site-packages\jedi\evaluate\imports.py", line 266, in sys_path_with_modifications
    sys_path_mod = self._evaluator.get_sys_path()
  File "C:\Python36\lib\site-packages\jedi\evaluate\__init__.py", line 125, in get_sys_path
    retval = self.project._get_sys_path(self, environment=self.environment)
  File "C:\Python36\lib\site-packages\jedi\evaluate\cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "C:\Python36\lib\site-packages\jedi\api\project.py", line 120, in _get_sys_path
    sys_path = list(self._get_base_sys_path(environment))
  File "C:\Python36\lib\site-packages\jedi\api\project.py", line 101, in _get_base_sys_path
    traceback.print_stack()
```
</details>

#### This behaviour will cause confusion / bugs as seen here:
https://github.com/jonathanslenders/ptpython/issues/248
https://github.com/jonathanslenders/ptpython/issues/246

#### I see two Problems:
1. Why is the code for removing `''` necessary?
2. I don't think Jedi completions should mutate the namespace argument at all.

**Comment by davidhalter** [comment]
I 100% agree that removing it from the mutable makes no sense. It should never have touched the sys path mutable. This means that we should create a copy before removing the item. Happy to receive a PR with a test.

If we're talking about removing the '' we have to think a bit more. This piece of code has been there for a long time. It has been there, because a lot of people start Jedi from some random place that might cause strange completions (the current working directory can be very strange at times).

**Comment by ju-w** [comment]
I'm not really comfortable about dealing with the way Jedi resolves all the implicit and explicit environment handling, sorry. :no_good_man:

Apparently, the removal of `''` was just introduced with the latest version.
Also I'm not sure about the implications of this.
If it means that this way we get no completions at all on the cwd, I bet most people (me included) would take the risk of 'strange completions' instead.

**Comment by davidhalter** [comment]
I removed the `sys.path` mutation. That one was extremely evil and of course unintended.

There was another question in this issue:

> Why is the code for removing '' necessary?

Removing it makes sense in some cases. Especially if we're talking about non-REPL environments. I could explain, but I'm a bit too lazy. The underlying reason is that sometimes a non-REPL environment gets started from very weird places. However something similar to `""` is added anyway so you shouldn't be having issues completing local imports.

Now for REPL users, you should let me know if this is good enough or if we still need to tune something. For me personally it works great now.

**Comment by kfrncs** [comment]
Updated to newest Jedi and this issue still exists for me.

**Comment by davidhalter** [comment]
As in a lot of other jedi-vim posts, your VIM/Python is somehow broken. Please downgrade or use a different version or something.

The problem is that Jedi won't work as long as you cannot do `:python3 import subprocess`. This is broken in your VIM and since subprocess is part of the standard library it's supposed to work.
