### ISSUE TITLE
Script: allow to set source and especially position

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1166]
When using `Script` for completion there appears to be quite some overhead when instantiating a new object all the time.

I think it would make sense to provide an API for setting the position (line/column).

Also setting the source / code_lines could be useful for when only a single line changes (i.e. while editing).

**Comment by davidhalter** [comment]
> I think it would make sense to provide an API for setting the position (line/column).

I'm quite clear on what I want to do there. `Script` will lose the line/column parameters and completions and all the other function will gain it. This will also be better for other APIs like `names` that can then be used from `Script`.

> Also setting the source / code_lines could be useful for when only a single line changes (i.e. while editing).

That is way more difficult, because that involves "diff" parsing (which already happens and which is the big overhead). So this is probably not going to happen, because it's technically almost impossible.

**Comment by blueyed** [comment]
Sounds good!

**Comment by blueyed** [comment]
It's a pity that updating the source is difficult, since for editors it is really common that only the current line changes.

**Comment by davidhalter** [comment]
@blueyed I know, but I think this is generally something that parsers have a hard time with.

I think Jedi tries already with the diff parser and we might even improve that in the future, but it's just generally not that easy to write algorithms that can deal with that well. I also think that the diff parser (in parso) is a pretty horrible hack. It works, but it's definitely not something I would generally recommend.

**Comment by davidhalter** [comment]
That was a lot of work:

```
74 files changed, 860 insertions(+), 780 deletions(-)
```

But I'm glad I did it. Had those changes in mind along time ago.
