### ISSUE TITLE
Script might throw ValueError for line / inconsistent line joining/splitting?!

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#1168]
I've seen a ValueError from Script (but have not taken note of it).

Looking at the code shows however that there might be an inconsisty because of `parso.split_lines` having special cases:

https://github.com/davidhalter/jedi/blob/9e66253e3a2aff6b9a96ebdd0c3b26639ecf4654/jedi/api/__init__.py#L123-L127

As for jedi-vim, deoplete-jedi etc we have to join the buffer's lines anyway, only for them to be split - and this might even cause offset errors then.

**Comment by davidhalter** [comment]
Can you give me an example where this fails? Or is problematic?

**Comment by blueyed** [comment]
Unfortunately not - but will take a note when it happens again at least.

**Comment by blueyed** [comment]
Just got it again, but hard to say what the issue is from the exception currently.

Added more info to the ValueError then, which showed that it appears to be a race / outdated information between line/col and the source when editing:

```
Error from jedi: ValueError('`column` parameter (38) is not in a valid range (0-35) for line 
93 ("            self.error(\'Error get\')\\n").',).
```

By that time the line was edited to be shorter already.

Therefore it is not a Jedi issue in this case, but the ValueError should be improved (will do).

But I still think that there might be a discrepancy, and that supporting a list directly makes sense.

**Comment by davidhalter** [comment]
Since I merged, is there still an issue here?

> But I still think that there might be a discrepancy, and that supporting a list directly makes sense.

I'm not sure if that's a good idea now, because all the API's at the moment (including parso) are not using a list and therefore everything Jedi would do is `''.join(lines)` if a list was provided (which wouldn't really improve anything). Maybe in some distant future we can change all of it. However I don't think that it's a performance issue at all and there are probably also issues with `\f` handling if we accepted lists. I think as a first step parso would need to support a list.
