### ISSUE TITLE
Namespace packages are not supported

### ISSUE THREAD

**Issue by flupke** [davidhalter/jedi#122]
Goto is tricked by namespace packages and fails.

I made tests to demonstrate this issue in https://github.com/flupke/jedi/commit/ad95279f1f5d160a22d5e07c1ced2a3011f39777

The problem is that `imp.find_module()` does not support namespace packages.

Should `imports.ImportPath._follow_file_system()` fiddle with `pkg_resources` (see http://stackoverflow.com/questions/5741362/alternatives-to-imp-find-module for a beginning of solution)? Or is `imp.find_module()` something you would like to discard in the future? (maybe by using `importlib.import_module()`, which does work with namespace packages, but has the disadvantage of actually importing the modules)

**Comment by sherwoodwang** [comment]
I'm using latest jedi-vim. It seems completion for `zope.interface` doesn't work.

When I use \<lead>d to find definition, it even throws an exception.

    Traceback (most recent call last):
      File "/Users/username/.vim/bundle/jedi-vim/jedi/jedi/_compatibility.py", line 24, in find_module_py33
        loader = importlib.find_loader(string)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/__init__.py", line 70, in find_loader
        raise ValueError('{}.__loader__ is None'.format(name))
    ValueError: zope.__loader__ is None
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/Users/username/.vim/bundle/jedi-vim/jedi_vim.py", line 110, in wrapper
        return func(*args, **kwargs)
      File "/Users/username/.vim/bundle/jedi-vim/jedi_vim.py", line 211, in goto
        definitions = [x for x in script.goto_definitions()
      File "/Users/username/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 364, in goto_definitions
        definitions = resolve_import_paths(definitions)
      File "/Users/username/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 338, in resolve_import_paths
        scopes.update(resolve_import_paths(set(s.follow())))
      File "/Users/username/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "/Users/username/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 94, in follow
        types = importer.follow()
      File "/Users/username/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "/Users/username/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 252, in follow
        return self._do_import(self.import_path, self.sys_path_with_modifications())
      File "/Users/username/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 281, in _do_import
        bases = self._do_import(import_path[:-1], sys_path)
      File "/Users/username/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 327, in _do_import
        find_module(import_parts[-1])
      File "/Users/username/.vim/bundle/jedi-vim/jedi/jedi/_compatibility.py", line 28, in find_module_py33
        raise ImportError("Originally ValueError: " + e.message)
    AttributeError: 'ValueError' object has no attribute 'message'

**Comment by davidhalter** [comment]
That's a bug, `ValueError really doesn't have an attribute `message`. We should probably replace this line with:

    ImportError("Originally " + repr(e))

Which looks better anyway.

**Comment by tbradshaw** [comment]
Is there any plan to add support for Namespace packages?  Our codebase uses Namespace packages (PEP 420) extensively and as a result jedi pulls up a blank on all of our code.

For the most part, now that PEP 420 works, we now only put __init__.py into packages that actually have some sort of initialization to perform.  Without them we have greater flexibility to compose python packages together.

However, it looks like pkgutil.iter_modules will never return is_pkg=True for Namespace packages.  (I'm not sure exactly how the import machinery in Python resolves them, instead, other than NamespacePath and NamespaceLoader are part of it.

**Comment by davidhalter** [comment]
> Is there any plan

No there isn't. Sorry :-) It works like this: Whoever really needs a feature will eventually implement it. I would really like to see this, but currently I don't really have time. I would be happy if you or someone else would take the lead here.

> However, it looks like pkgutil.iter_modules will never return is_pkg=True for Namespace packages.

In general, I'm not sure if this is the right way to find that information, because quite frankly I have no clue how Python finds those packages. IMO we should implement it the same way Python implements this anyway, which would mean first investigating how Python does it (even if it's C code, which I don't believe, because it's probably in `importlib.py`.

**Comment by tbradshaw** [comment]
Understood.  If I were to submit a patch for the documentation for "Unsupported Features", would you prefer namespace packages to be listed in the subsection "Not yet implemented" or "Will probably never be implemented"?

With namespace packages being an integral feature of Python 3, it was a surprise that a code analysis tool of this caliber doesn't support it.  (Completely understandably, after reading how the code for jedi handles imports.)  A lot of time could be saved if it were in the feature list.

**Comment by davidhalter** [comment]
It's a question of priorities. I don't have the time to do it right now, but it will definitely be implemented at some point in time. Therefore it's definitely not a "Will probably never be implemented". In general there's a need for people besides me improving Jedi, this could be a good start. :)

**Comment by sruggier** [comment]
I'm using jedi as part of [YouCompleteMe](/Valloric/YouCompleteMe). The codebase I'm working with has a nested set of packages that looks like `namespace1.namespace2.regular1.regular2.regular3`. The `__init__.py` in each of the two namespace packages contains code like this:
```
try:
    import pkg_resources
    pkg_resources.declare_namespace(__name__)
except ImportError:
    import pkgutil
    __path__ = pkgutil.extend_path(__path__, __name__)
```

When I type `import namespsace1.`, the completion list properly includes `namespace2 as a proposal, even though it's not the first package in that namespace. However, the completion list is empty for `import namespace1.namespace2.`. Finally, if I try to complete on import namespace1.namespace2.regular1.`, Jedi experiences an internal error, because this snippet of code returns an empty list of paths:
```
                # It's possible that by giving it always the sys path (and not
                # the __path__ attribute of the parent, we get wrong results
                # and nested namespace packages don't work.  But I'm not sure.
                paths = base.py__path__(sys_path)
```

Is that related to this issue, or should I file a new one?

**Comment by davidhalter** [comment]
You probably don't need to create an issue for this, because it's very unlikely that anyone else will tackle it, also it's kind of in this issue.

**Comment by davidhalter** [comment]
AFAIK Namespace packages are now supported.

**Comment by elprans** [comment]
> AFAIK Namespace packages are now supported.

Support for nested namespace packages is still broken: https://github.com/elprans/jedi/commit/ca10e1702427d72a67072f600a646c324e6beadc

**Comment by gustavovalverde** [comment]
After testing with commit https://github.com/m-novikov/jedi/commit/869c72d6350a87834f54d6229d859e19499466c5 I can validate that this is not completely working yet.

**Comment by davidhalter** [comment]
With the help of a few pull requests everything is now working fine. Let me know if there are still issues. It's all on the master branch.

@gustavovalverde It's working perfectly fine. I just checked. You just have to use the right Python version.

**Comment by brokenn** [comment]
Hi, 

I'm failing to get autocompletion working via VSCode/Jedi with a large internal namespace package. I've managed to boil it down to a small example with just Jedi. 

I have a namespace package called 'foo', spread across two directories, 'projecta' and 'projectb'

```
$ tree
.
├── projecta
│   └── foo
│       ├── bar
│       │   └── __init__.py
│       └── __init__.py
└── projectb
    └── foo
        ├── baz
        │   └── __init__.py
        └── __init__.py
```

The foo/\_\_init\_\_.py file is identical across both directories:

```
$ cat projecta/foo/__init__.py 
import pkg_resources
pkg_resources.declare_namespace(__name__)

$ cat projectb/foo/__init__.py 
import pkg_resources
pkg_resources.declare_namespace(__name__)
```
And foo/bar/\_\_init\_\_.py and foo/baz/\_\_init\_\_.py contain a single function each:
```
$ cat projecta/foo/bar/__init__.py 
def bar():
  return 'bar'

$ cat projectb/foo/baz/__init__.py 
def baz():
  return 'baz'
```

The namespace packages work in Python as I would expect:
```
$ PYTHONPATH=projecta:projectb python
>>> import foo; import foo.bar; import foo.baz
>>> foo.bar.bar(), foo.baz.baz()
('bar', 'baz')
```

But autocompletion with Jedi is only working for one of the two packages, always the first to be listed in the search path. For example, here it will complete for foo.bar.bar() but not foo.baz.baz()

```
$ PYTHONPATH=projecta:projectb python
>>> source = '''
... import foo; import foo.bar; import foo.baz
... a = foo.bar.b
... b = foo.baz.b
... '''
>>> import jedi
>>> [x.complete for x in jedi.Script(source, 3, 13, '').completions()]
[u'ar']
>>> [x.complete for x in jedi.Script(source, 4, 13, '').completions()]
[]
```

And with the Python Path swapped around, it will complete for foo.baz.baz() but not foo.bar.bar()
```
$ PYTHONPATH=projectb:projecta python
>>> source = '''
... import foo; import foo.bar; import foo.baz
... a = foo.bar.b
... b = foo.baz.b
... '''
>>> import jedi
>>> [x.complete for x in jedi.Script(source, 3, 13, '').completions()]
[]
>>> [x.complete for x in jedi.Script(source, 4, 13, '').completions()]
[u'az']
>>> jedi.__version__
'0.12.0'
```

This is with Jedi 0.12.0

It's entirely possible I've done something wrong and any advice would be appreciated if that is the case. If what I've done is right, I would contend that this bug is not entirely fixed yet. Please let me know if you need any more information.

**Comment by brokenn** [comment]
Sure thing, opened as #1105
