### ISSUE TITLE
Jedi crashes in REPL with jedi applied via PYTHONSTARTUP on python 3.7 OSX 10.13

### ISSUE THREAD

**Issue by jmfrank63** [davidhalter/jedi#1240]
I've got a strange issue. On my Mac, OS 10.13 python 3.7.0 I get this:
```
09:02 $ python
Python 3.7.0 (default, Jul 29 2018, 18:10:54)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
REPL completion using Jedi 0.13.1
>>> import jedi
>>> script = jedi.Script("import trio;s = trio.socket.")
>>> cmp = script.completions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johannes/Envs/trio-LVKXRiL_/lib/python3.7/site-packages/jedi/api/__init__.py", line 177, in completions
    self._pos, self.call_signatures
  File "/Users/johannes/Envs/trio-LVKXRiL_/lib/python3.7/site-packages/jedi/api/completion.py", line 91, in __init__
    self._like_name = helpers.get_on_completion_name(self._module_node, code_lines, position)
  File "/Users/johannes/Envs/trio-LVKXRiL_/lib/python3.7/site-packages/jedi/api/helpers.py", line 27, in get_on_completion_name
    leaf = module_node.get_leaf_for_position(position)
  File "/Users/johannes/Envs/trio-LVKXRiL_/lib/python3.7/site-packages/parso/tree.py", line 310, in get_leaf_for_position
    raise ValueError('Please provide a position that exists within this node.')
ValueError: Please provide a position that exists within this node.
>>>
```
If I unset `PYTHONSTARTUP` before starting python it works.
Also if I redefine the script a second time after the crash and call the completions method again it works as well.
The issue is obviously minor you can work around easily, but I thought you might want to know.

**Comment by davidhalter** [comment]
> The issue is obviously minor you can work around easily, but I thought you might want to know.

Yes I do, this feels however very very weird. Would you be able to debug this a bit more for me and check what position is in api/helpers.py? That would be helpful. I cannot really reproduce it.

**Comment by jmfrank63** [comment]
Hi David,

sure, I made some tests. The position seems to be always (1, `<length of string>`) This is very likely correct. 
However I found that the failure only occurs if there is an assignment with correct python spacing inside the string. So for example `"import os;v = os."` fails while `"import os;os."` does not nor does `"import os;v=os."` .
There might be another dependency as it seemed to me that sometimes the error does not occur if I do not utilise the tab completion from the command line, but that might be a "superstition in pigeon" effect as I had at least one case where the error occurred without me using tab completion.

So my guess would be to look at the spaces around the assignment.
But on the weirdness scale I assume this takes a top rank ;-)

**Comment by davidhalter** [comment]
Is this still happening with 0.14.0 and parso 0.5.0? Please make sure you have both :)

**Comment by jmfrank63** [comment]
Just tested this again now being on OSX 10.14.5. At first with 0.13.2 where after pasting in my old commands everything went fine. I repeated the command again and it worked.
Then I typed in the command via `cmp = script.comp<tab>()`
and I got the traceback again.

I upgraded to 0.14 and parso 0.5.0 and tested again:
```
╰─ python
Python 3.7.2 (default, Feb 18 2019, 21:28:58)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
REPL completion using Jedi 0.14.0
>>> import jedi
>>> script = jedi.Script("import trio;s = trio.socket.")
>>> cmp = script.completions()
>>> cmp = script.completions()
>>> cmp = script.completions()
>>> cmp = script.completions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johannes/.pyenv/versions/3.7.2-jedi/lib/python3.7/site-packages/jedi/api/__init__.py", line 214, in completions
    self._pos, self.call_signatures
  File "/Users/johannes/.pyenv/versions/3.7.2-jedi/lib/python3.7/site-packages/jedi/api/completion.py", line 92, in __init__
    self._like_name = helpers.get_on_completion_name(self._module_node, code_lines, position)
  File "/Users/johannes/.pyenv/versions/3.7.2-jedi/lib/python3.7/site-packages/jedi/api/helpers.py", line 28, in get_on_completion_name
    leaf = module_node.get_leaf_for_position(position)
  File "/Users/johannes/.pyenv/versions/3.7.2-jedi/lib/python3.7/site-packages/parso/tree.py", line 312, in get_leaf_for_position
    raise ValueError('Please provide a position that exists within this node.')
ValueError: Please provide a position that exists within this node
```
The issue only appears when using tab completion to get `script.completions()` when using the history via the arrow keys everything is fine.

if you want me to do any further debugging let me know. I appreciate the great work you have done on Jedi this is weird and can easily be worked around.

**Comment by davidhalter** [comment]
WTF. I can reproduce it now. Thanks!

**Comment by davidhalter** [comment]
Ok. I understand now what it is.

Basically Jedi is not thread-safe and it's also pretty much not working with multiple `Script` instances that are alive at the same time.

The problem is basically that the "fast parser" that parso uses is reusing "old" module objects. In this case the wrong code is used in the end.

This is really bad - but at the same time it's not. I have known about this problem, but people really don't use multiple `Script` instances at the same time. It's just not something that's needed.

Not saying that we shouldn't correct that, but it's not that easy. I would have to rewrite quite a few things. Parsers exist that solve this problem (no idea if the performance is still as good, but at least the implementation will probably not be as ugly), however it's also not easy. I think C#'s Roslyn has a pretty good approach to parsing files, without re-parsing everything all the time. For now, this is just not going to work, but I hope I can fix it in the future.

If you just want to get rid of this weird behavior, use `jedi.settings.fast_parser = False` and you're good.

**Comment by jmfrank63** [comment]
Hi Dave,

thanks for your efforts on this. The question is, is this something I could
help with? I am not a star coder, but I usually get it done after asking a
lot of questions. If you give me some heads up, I'd give it a try.

Thanks

Johannes

**Comment by davidhalter** [comment]
Hi Johannes

You don't have to be a star coder for most parts of Jedi, feel free to fix any issues :)

This is just one of the issues I wouldn't begin with. It has to do with parsing, so if you're not used to write LL(*) parser generators (really, who is?), this is no easy task already. If you know about that, you can start reading about Roslyn and libsyntax. This is a good introduction: https://github.com/apple/swift/tree/5e2c815edfd758f9b1309ce07bfc01c4bc20ec23/lib/Syntax red/green trees.

The thing with this is that I'm not sure it's efficient. The current solution is really efficient and works well for a lot of use cases. So there's also a balance to strike. I would estimate that it takes at least two weeks. I would probably estimate a month in total.

So be my guest, but don't expect too much help, because I myself don't really have the knowledge (yet). It's pretty much the hardest thing within Jedi. However I'm happy to point you to other tickets that are easier :)

 ~ Dave

**Comment by davidhalter** [comment]
Looked at this again.

It looks like the only viable solution for now is to use something like `deep_ast_copy` like this:

```
diff --git a/parso/grammar.py b/parso/grammar.py
index c943a52..daf539b 100644
--- a/parso/grammar.py
+++ b/parso/grammar.py
@@ -125,6 +125,7 @@ class Grammar(object):
                 if old_lines == lines:
                     return module_node
 
+                module_node = deep_ast_copy(module_node)
                 new_node = self._diff_parser(
                     self._pgen_grammar, self._tokenizer, module_node
                 ).update(
```

The problem with this change is that it leads to way slower performance for a Python file with 40kLoC:

- without diff_cache 9808 ms
- with diff_cache 188 ms
- with diff_cache and patch 3503 ms

Since this bug hasn't really caused any major problems I'm going to ignore it for now. It's unfortunate, but it's just not important enough.

For the future, I wrote this test to reproduce it:

```
def test_module_duplication(Script):
    """See #1240"""
    script1 = Script('str\nstr', path='/foo')
    script2 = Script('str', path='/foo')
    # Now use actions that alternate scripts.
    assert script1.infer()
    assert script2.goto()
    assert script1.goto(line=1)
```

**Comment by jmfrank63** [comment]
Hi David,

I think ignoring this is fine for now. I am pretty tied up at the moment,
but if you don't mind I am adding this to the end of my list. It is thread
related and I am weak with threads.
Therefore approaching this will like make me a little better in threads.

But to be honest I don't see myself having time for this withing the next 3
possibly 6 month.

And by the way happy new year!

Thanks

Johannes
Dipl.-Ing. (FH) Johannes-Maria Frank
17 Orchard Drive
Uxbridge
UB8 3AE
United Kingdom
phone: +447400987848
e-mail: jmfrank63@gmail.com

**Comment by davidhalter** [comment]
@jmfrank63 It's not a thread problem, it's a mutable datastructure issue in parso. There are no threads involved.

Note that this is not really fixable unless you rewrite software completely (probably with a performance penalty). So happy to have you contribute somewhere, but this probably makes no sense :)

**Comment by davidhalter** [comment]
After further analyzing this, I realized that working with immutable data structures is too big of a performance penalty for now. This is unfortunate, but I feel like it's not really an issue for most (if not all) users and people really really want that performance.

So I'm not fixing it. For people that want to avoid this issue, just write `jedi.settings.fast_parser = False` and you will be good. There's a lot of additional documentation now. I hope that helps as well.
