### ISSUE TITLE
safety checks break virtualenv, but don't appear to provide any safety?

### ISSUE THREAD

**Issue by glyph** [davidhalter/jedi#1250]
My (emacs) jedi installation broke today when I upgraded it, because none of my virtual environments in ~/.virtualenvs are "safe", despite explicitly passing them to `jediepcserver` via `--virtual-env` and/or `VIRTUAL_ENV=`.

I understand concern around potentially nasty things that attacker-controlled Pythons might do, and care that must be taken when selecting what paths to execute (and avoiding relative paths, since a user might be running their editor to inspect some nasty malware!) but the threat model articulated in `environment.py` doesn't make sense to me.

My understanding is that if Jedi searches random paths for `bin/python`, the fact that the checksum happens to match a "safe" version doesn't matter - this attacker also presumably has the ability to write to `lib/`, which means they can stuff in a nasty `site.py` to do arbitrarily bad things.  The line "The bin/python is obviously not a python script but a bash script" is particularly perplexing, as obviously arbitrary Python code can do arbitrary bad things and doesn't need help from bash.

I have plenty of Pythons installed in "unsafe" ways - Homebrew python isn't owned by root, neither are any of the ones I've installed with pyenv.  None of them are installed to relative paths inside checked-out repositories, however, and I'm quite sure that I do want to run them.

**Comment by glyph** [comment]
It seems to be possible to work around this for now by setting `$PATH` in the subshell that invokes the server (specifically this, in the python-mode hook before `jedi:setup`) rather than passing a command line argument, like so:

```
(setq-local jedi:server-command
                      (append (list "env"
                                    (concat "VIRTUAL_ENV=" env-to-use)
                                    (concat "PATH=" env-to-use "/bin:" (getenv "PATH")))
                              jedi:server-command))
```

(I realize that this is a very Emacs-specific workaround, but hopefully if someone is having the same issue in jedi-vim they can translate.)

**Comment by spookylukey** [comment]
For those like @glyph using emacs-jedi, this appears to be fixed from emacs-jedi, due to this commit - https://github.com/tkf/emacs-jedi/commit/db0a651c42f4f55f3985d2f037a74f1893d94a82 - which was introduced to fix something else. But it now disables the safety check, which gets around the problem.

**Comment by jkoelndorfer** [comment]
Jedi autocompletion in vim broke for me recently when I incorporated `pyenv` into my workflow. It puts a Python shim script in the user's home directory so that it's easy to switch Python versions for different projects.

Since the shim is in my `PATH`, the implication is that the binary is safe to run. If it weren't, then I have misconfigured my `PATH` or an attacker has the ability to change my `PATH`. In either case, jedi is not actually providing me any extra security.

Is there an easy workaround for this for vim-jedi users? I did not find anything after a brief look. I would like to continue to leverage pyenv since I am working on several different projects which have different minimum Python version requirements.

**Comment by davidhalter** [comment]
I'm still not entirely sure that lifting the `safe=True` barrier is a good idea.

However, I still want to make it easier to deal with multiple environments in jedi-vim. The tools are all there, we just need to write it.

Also: Would you use something like `let jedi#set_safe_true = 1`.

**Comment by jkoelndorfer** [comment]
I would be more than happy with an option to let me turn it off. It's easy enough to add to a vimrc.

**Comment by davidhalter** [comment]
@glyph First of it all, sorry for the long delay. There have been a lot of pressing issues for Jedi, so I finally got around to thinking about this a bit more.

>  The line "The bin/python is obviously not a python script but a bash script" is particularly perplexing, as obviously arbitrary Python code can do arbitrary bad things and doesn't need help from bash.

Yes, this line was confusing. I slightly changed it to `The attacker has gained code execution, since he controls foobar/bin/python.`

I think we might have fixed "your" issues a while ago actually. Since you are always setting `VIRTUAL_ENV=...`, it should work without setting `safe=False`. This has been changed in 56bd7951005778a7c5dd299fdadaa2c372165fd4, (https://github.com/davidhalter/jedi/pull/1199). The reason for this change was pretty simple: If an attacker controls shell variables, you're probably screwed anyway. I don't see why an attacker would ever gain access to this, while it makes a lot of sense that an attacker could control some local files.

I still don't get why setting `PATH` ever helped you. IIRC we never did anything with it. It shouldn't matter.

For `create_environment(..., safe=True)` and `find_virtualenvs(..., safe=True) I still think the default is sane. It's just too easy otherwise to get code execution. Editors/IDEs can decide differently, but I feel like I owe it to users to give them this option (and I'd rather be safe by default than not).

Does this make sense? Or do you still disagree?

-----

@jkoelndorfer 

> I would be more than happy with an option to let me turn it off. It's easy enough to add to a vimrc.

Please open an issue in jedi-vim then. This is not something we can do in Jedi (and I will definitely forget about it if there's no issue).

**Comment by glyph** [comment]
> Does this make sense? Or do you still disagree?

I still disagree, but only because I don't understand the threat model here.  What exactly is the attack here?  How does the attacker get control of your Jedi virtual environment to write arbitrary scripts into it, but *not* already have arbitrary code exec on your whole machine?  I don't understand *what* this is defending against.

**Comment by davidhalter** [comment]
It defends against 

```
git clone https://github.com/random_dev/attacker_repo
cd attacker_repo
# Open Editor, editor uses Jedi
>>> jedi.find_virtualenvs()
# At this point the `attacker_repo/bin/python` was executed, which was an executable that the attacker provided.
```

The attack is basically that downloading and working with arbitrary code in Jedi is not safe without `safe=True`.

**Comment by glyph** [comment]
Aah, thank you for the succinct problem statement.

if this is the threat model, then why would you ever have `find_virtualenvs` even *look* in a potentially attacker-controlled directory for a virtualenv?

**Comment by davidhalter** [comment]
The problem is that Jedi users (editor plugins) generally just use Jedi without much caution.

At some point there need to be safeguards and I feel like having them in Jedi makes more sense than having them in each library. If editor plugins know they are doing safe stuff, they can always add `safe=False`.

As I said before:

> I think we might have fixed "your" issues a while ago actually. Since you are always setting VIRTUAL_ENV=..., it should work without setting safe=False.

With this and my argumentation above I feel like this issue has been resolved and no more actions need to be taken. But feel free to keep the discussion going.

**Comment by glyph** [comment]
@davidhalter Sounds good.

I think the real action item here might be just to write a document on Jedi's security model - how it understands that a directory is safe, how it decides what code to execute, etc.  I suspect that the right thing to do would not so much be to have a notion of an "unsafe" environment, but rather to refuse to load such an environment in the first place.

**Comment by jkoelndorfer** [comment]
@davidhalter:

Re:

> I still don't get why setting PATH ever helped you. IIRC we never did anything with it. It shouldn't matter.

Setting `PATH` does not help anything with regards to Jedi. It is what permits `pyenv` to work.

The point I was driving at was if I have configured `PATH` such that the binary that Jedi is evaluating is in the `PATH`, then Jedi should assume that the binary is safe.

**Comment by davidhalter** [comment]
> I suspect that the right thing to do would not so much be to have a notion of an "unsafe" environment, but rather to refuse to load such an environment in the first place.

I mean, I theoretically agree. But how would you do that? 

> The point I was driving at was if I have configured PATH such that the binary that Jedi is evaluating is in the PATH, then Jedi should assume that the binary is safe.

@jkoelndorfer Ok. I understand now. Is this still an issue for you? If it is I'm happy to add that. I would consider executables on path to be safe.

**Comment by glyph** [comment]
> > I suspect that the right thing to do would not so much be to have a notion of an "unsafe" environment, but rather to refuse to load such an environment in the first place.
> 
> I mean, I theoretically agree. But how would you do that?

I suspect that I do not have a strong enough grasp of Jedi's internals to make a coherent proposal without a clear understanding of the security model it's trying to preserve — so it's tempting to make suggestions but I worry I'd be wasting your time :).

**Comment by davidhalter** [comment]
@glyph Well, I feel like there are ways to do most things statically, but that has other drawbacks. So, yes, it's possible, but it's just a lot of work.

**Comment by jkoelndorfer** [comment]
> @jkoelndorfer Ok. I understand now. Is this still an issue for you? If it is I'm happy to add that (or even happier to accept a pull request). I would consider executables on path to be safe.

I worked around the issue in my own dotfiles, but it causes vim to use the system Python rather than the version that the project calls for: https://github.com/jkoelndorfer/dotfiles/blob/master/bin/nvim#L9. 

That workaround has been performing well enough for me to get by. But I do think that using the project's Python version is the right way to go. If I can dig up some motivation, I'll see if I can implement this and submit a PR -- shouldn't be too difficult. No promises, though. :-)

**Comment by davidhalter** [comment]
Reopening so I don't forget about this.

**Comment by jkoelndorfer** [comment]
Good ol' software development.

Made the tweaks required for my proposal and wrote some tests, only to discover that I wasn't actually able to reproduce the problem anymore. I'll do some more experimenting and see if I am able to reproduce. If so, will open a PR for the work I did.

Cheers to a great project. It was easy to start hacking!

**Comment by jkoelndorfer** [comment]
I got rid of the workaround in my dotfiles just after my previous comment and haven't yet been able to reproduce the old behavior I saw where Jedi got mad about python binaries supplied by pyenv.

¯\_(ツ)_/¯

**Comment by davidhalter** [comment]
I guess I'll close then :) Just open a new issue if you are having the problem again.

For now I don't think we need to change anything (as long as nobody complains, which hasn't happened for a long time).
