### ISSUE TITLE
Another invalid escape sequence

### ISSUE THREAD

**Issue by Julian** [davidhalter/jedi#1261]
https://github.com/davidhalter/jedi/blob/master/jedi/evaluate/arguments.py#L95 is an invalid escape sequence (``\[``) which presumably again intends to be a raw string.

You might want to run your tests with PYTHONWARNINGS=default to catch these sorts of things (of course happy to send a PR doing that).

**Comment by davidhalter** [comment]
The strange thing is that I see the line but there is no warning. I see where there should be a warning, but pytest doesn't show one.

What I found is that the function you're pointing to, is executed on import. Therefore it's never actually triggered while running tests. It should be triggered before tests, but that's unfortunately not happening. I think this is probably an edge case and I just fixed it.

I also don't think we need to use PYTHONWARNINGS=default, because that triggers some pytest warnings - which are not "my" problem. We're probably fine.

However if you want to do some digging, I wasn't able to see this warning anywhere with this `
PYTHONWARNINGS=default python3.7 -m pytest -s` before my commit.

**Comment by davidhalter** [comment]
I just realized that the issue why I couldn't find it was this one: https://bugs.python.org/issue30091 

Using this solved:
```
rm jedi/evaluate/__pycache__/ -r
```

I guess it's bound to happen again - sorry, it's unfortunate that the warning is not always shown... Even if I used `-W error`, it would only happen the first time it's run, so it's pretty much a lost cause.
