### ISSUE TITLE
Missing completion for numpy

### ISSUE THREAD

**Issue by louisabraham** [davidhalter/jedi#1265]
Hi, I have some problem with numpy completion.

jedi==0.13.2
numpy==1.15.2
numpydoc==0.8.0

Some symbols are not completed, like float32. (note that numpy.array is completed)

**Comment by davidhalter** [comment]
This is likely not going to improve as long as there are no stubs., because float32 is set with `global()[...] = `. It's not really possible to understand that:

https://github.com/numpy/numpy/blob/v1.15.4/numpy/core/numerictypes.py#L879

The solution is to use something like this in the future:

https://github.com/numpy/numpy-stubs/blob/master/numpy-stubs

However #839 has not been completed yet, so that's not even possibe.
I'm closing in favor of #839.
