### ISSUE TITLE
Some imports not listed in auto-completion

### ISSUE THREAD

**Issue by Jeansen** [davidhalter/jedi#1346]
I've installed urwid (http://urwid.org/tutorial/index.html) via pip. The same way I installed for instance pyqt5.

But with vim, deoplete and deoplete-jedi I do not get any completion that shows me urwid. The static analysis tells me `unable to import urwid`. pygq5 works fine, though.

Also other packages show up, e.g. `uuid` or `urllib` when I type `u...`

**Comment by davidhalter** [comment]
Please post the issue with a failure from direct Python calls. If `jedi.Script('import urwid').completions()` doesn't work, it's maybe a Jedi issue. Otherwise go to your plugin project and report it there.

I'm pretty sure that you are not using environments the right way and you're probably completing in Python 3.5 while you've installed it in Python 3.6 or something like this (or a virtualenv is not activated). However this issue has probably nothing to do with Jedi. Closing until you provide further proof.
