### ISSUE TITLE
pow() signature changed in 0.14.0

### ISSUE THREAD

**Issue by ericsnowcurrently** [davidhalter/jedi#1357]
Here's what I ran (using Python 3.6):
```python
import jedi
script = jedi.Script('pow()', 1, 4, 'script.py')
sig = script.call_signatures()[0]
for param in sig.params:
    print(param)
```

Using 0.14.0, I get the following output:
```
<Definition full_name=None, description='param __x: float'>
<Definition full_name=None, description='param __y: float'>
<Definition full_name=None, description='param __z: float'>
```

Those leading underscores are unexpected.  Before 0.14.0 (e.g. 0.13.3) the parameter names were reported as "x", "y", and "z", which is what I would expect.  Also, `help(pow)` shows the expected signature: `pow(x, y, z=None, /)`.

**Comment by davidhalter** [comment]
Hmm just a bit of context before we start changing things: This is the signature that you would find in typeshed.

Now I agree that it might feel strange, but typeshed's idea for params with double underscore is that they are positional only (what the slash also says, but which is not valid before Python 3.8).

So I'm not sure if we should change something there, because it's actually official typeshed. I'm pretty confident this will eventually move to the `pow(x, y, z=None, /)` signature. The question is probably if we want to scan for this `__` pattern and move a slash in there.

**Comment by ericsnowcurrently** [comment]
Thanks for the explanation, @davidhalter.  I see what you mean.  There is certainly value in communicating to users that an argument is positional-only (ditto for keyword-only).  The question is how.  For most folks the leading `__` won't mean much.  Where users are concerned, it would be better to keep the actual name and show them "(positional-only)" nearby.

I realize this is partly a consequence of using typeshed (which mostly need not change) and not even necessarily a concern of Jedi.  If each `CallSignature` param indicated if it was positional-only (see #1361) then the leading `__` could be dropped.  I can do that on my end, but it seems like something all Jedi users would want.

**Comment by davidhalter** [comment]
Yeah, I can probably just rewrite this internally. Need to think about it for a bit.

**Comment by ericsnowcurrently** [comment]
Thanks, @davidhalter!  That helps.  From what I can tell, `param.name` still has the leading `__`:  `<Definition name='__x', description='param x: float'>`.

Also, how do I access the parameter kind via the API (i.e. `jedi.api.classes.Definition`)?

**Comment by ericsnowcurrently** [comment]
Thanks!
