### ISSUE TITLE
CallSignature.index isn't right for *args.

### ISSUE THREAD

**Issue by ericsnowcurrently** [davidhalter/jedi#1363]
Currently the index advances with each further positional arg (rather than staying the same).

So in each of the following cases (where the cursor is at the end) the index should be 0:

* `print(`
* `print(a `
* `print(a, `
* `print(a, b, c`
* `print(a, b, c, `

However, once there's a keyword argument , the index should no longer be 0:

* `print(a, sep=`

(on typeshed: `def print(*values: object, sep: Text = ..., end: Text = ..., file: Optional[_Writer] = ..., flush: bool = ...) -> None`)

**Comment by davidhalter** [comment]
CallSignature.index has been broken ever since Jedi existed. I finally had a look at it.

I fixed a ton of issues around this and added a big number of test cases: https://github.com/davidhalter/jedi/blob/master/test/test_api/test_call_signatures.py#L404-L499

Please let me know if there's still issues for this.
