### ISSUE TITLE
Add support for rst-formatted docstring tooltips

### ISSUE THREAD

**Issue by bjtho08** [davidhalter/jedi#1366]
In vscode, when using jedi, there is an issue with properly rendering the docstring tooltips if they use the rst format.
![jedi-vscode](https://user-images.githubusercontent.com/885853/60792533-291ccc00-a166-11e9-9bc7-d0010688673d.png)
Since rst is the "official" Python dosctring format, I suggest adding support for the format.

**Comment by davidhalter** [comment]
What is the issue? Since when is rst the "official Python docstring format?

**Comment by bjtho08** [comment]
The issue is that the tooltip completely lacks formatting according to the fields supplied by the actual docstring. I might be wrong, but I'm sure I've read it in several places that rst is the recommended docstring format due to its verbosity and I noticed that jedi internally use it as well, so it would seem reasonable that tooltip rendering also support rst.

**Comment by mpanarin** [comment]
> What is the issue? Since when is rst the "official Python docstring format?

https://www.python.org/dev/peps/pep-0287/

**Comment by davidhalter** [comment]
Jedi doesn't do any processing of these docstrings. The visual studio code team asked me to do it here

https://github.com/davidhalter/jedi/issues/1330

This is the upstream issue:

https://github.com/microsoft/vscode-python/issues/5633

As you can see, @luabud mentioned that they are doing processing for this kind of stuff now, so that might be your issue.

I'm slowly realizing that doing processing is not a good idea, because it breaks quite a few peoples docstrings. So I will close this issue and probably the other one as well.
