### ISSUE TITLE
Interpreter completions ignore nested dynamic entries (__getattr__)

### ISSUE THREAD

**Issue by filmor** [davidhalter/jedi#1378]
Taking the example from #1027 and modifying it slightly such that we have nested objects, jedi fails to complete after the first level:

```python
class CompleteAttrs(object):
    def __getattr__(self, name):
        if name == 'foo':
            # Used to be return 1
            return self
        if name == 'bar':
            # Used to be return 2
            return self
        raise AttributeError(name)
    
    def __dir__(self):
        return ['foo', 'bar'] + object.__dir__(self)

from jedi.api import Interpreter

# This works
itp = Interpreter("ca.", [{'ca': CompleteAttrs()}])
for c in itp.completions():
    print(c.name)

# This doesn't
itp = Interpreter("ca.foo.", [{'ca': CompleteAttrs()}])
for c in itp.completions():
    print(c.name)
```

I've tried this with version 0.14.1. In #1027 I couldn't see what was done to fix that issue, so I don't really know where to start to fix this problem.

**Comment by davidhalter** [comment]
The problem with this is that it's not easily fixable, because it's extremely unsafe. It would execute arbitrary code in `__getattr__` if we just executed it. We could of rcourse do that, but it's intentionally not done. 

We are having similar discussions in #1299.

**Comment by filmor** [comment]
Ah, now I get it. I could add a "top-level dir", i.e. a function that could provide the result of `__dir__` on any nesting level that jedi could pick up instead of `__dir__`, something `def __jedi_dir__(self, path: List[str]) -> List[str]` where `obj.__dir__() == obj.__jedi_dir__([])` and the given case of `ca.foo.` would be `obj.__jedi_dir__(["foo"])`.

**Comment by davidhalter** [comment]
Just wondering: Is this really that important for you, that you would write that kind of code?

Also, would you enable a `safe=False` option, if you could?

**Comment by filmor** [comment]
It is important to me, yes :)

We have a nested structure of queries that is provided to the users in IPython. The easy discoverability of these queries is based on being able to tab your way through, which used to work before (and still does with `Completer.use_jedi=False`, but that way we 1. need to configure it and 2. lose all of the advantages of Jedi).

**Comment by BrenBarn** [comment]
I feel that the safety issue is a total red herring here.  If I type `foo.bar.<TAB>` and don't get a completion, the first thing I'm going to do is do `x = foo.bar` and then try to do `x.<TAB>`, thus evaluating the "unsafe" attribute and suffering the consequences.

Autocompletions simply do not need to be safe.  If you are importing a module and using it you are already exposed to whatever malice it may contain.  The "safety" reasoning seems to imply a view that people are going do `import evilmodule`, find they can't autocomplete `evil_object.evil_prop`, and then give up and go home, which to me is highly unrealistic.  Of course what they're going to do is evaluate the `evil_prop` some other way and get hurt.  They already imported the module and tried to access the property because they want to use it because they don't know it's malicious.  Not autocompleting isn't going to warn them the attribute is malicious, and refraining from evaluating due to safety concerns just teaches people to manually evaluate expressions to be able to autocomplete them, because 99% of the time what they're trying to autocomplete isn't malicious so they'll assume it's just another case of the autocompleter failing to complete something they want it to complete.

The only way to know if an object is malicious is to read the source code.  No one is going to react to a failed autocomplete by stopping what they're doing and going to read the source code to check if the attribute is malicious.  It's just way more important to get full completions than to be careful about evaluating things.  It's fine to evaluate everything you need to to get all the completions.

If there were a `safe=False` option I would set it as the default.  The only time I care about not evaluating things is not for safety but simply for time's sake.  For instance, if I'm dealing with an object where accessing the property may trigger a computationally expensive operation that will cause a delay, I'd like to be able to not trigger that.  But that's a tiny minority of cases.

**Comment by davidhalter** [comment]
> Autocompletions simply do not need to be safe.

There are two issues with this:
1. Not all people think like you and some people will be very surprised that Jedi just executes things.
2. The protection we implemented for Jedi was not about security, it's about safety. People sometimes put stuff behind properties or other things that take a long time to compute or might execute something that should never have been executed.

However since most of the protection for (2) seems to have been removed by #1299, it's questionable why we still hold onto protection here (at least for `jedi.Interpreter` usages, which IPython uses).

**Comment by BrenBarn** [comment]
> 1. Not all people think like you and some people will be very surprised that Jedi just executes things.

You may be right, but I think not all people think like you either :-).  On the related thread in jupyter/notebook#2435 a lot of people are complaining that autocomplete "stops working".  As you noted there, such complaints are often very vague.  However, I would guess that a fair number of people are encountering situations like this and just aren't aware (and/or don't take the time to debug) that it's specific to certain types of attributes.  They just can't autocomplete things that they want to, and don't realize it's because the attributes aren't "real" attributes.

This is especially true for pandas users because pandas makes heavy use of nested attribute/method chains.  In fact, it's precisely because of those long chains that autocomplete becomes most essential.

I think what a lot of people expect is that if it's possible to evaluate `a.b.c`, then doing `a.b.<TAB>` should autocomplete `c`.  That's it.  Of course there are cases where this actually can't be done (for instance, there's no way to autocomplete on "fake" attributes where all the accessing logic happens in `__getattr__` code), but I think it should be done as much as possible, evaluating whatever is necessary to make it happen.

> 2. The protection we implemented for Jedi was not about security, it's about safety. People sometimes put stuff behind properties or other things that take a long time to compute or might execute something that should never have been executed.

What distinction are you drawing between security and safety?  I think all that I said in my earlier comment applies to safety (and indeed I used the word "safety", as you previously did).  Yes, people sometimes put stuff behind properties that is expensive to compute.  The point is that such cases are far less common than the situation where the property is not expensive to compute and people want to compute it and autocomplete on it.  So it makes sense for the default to be to autocomplete these things.  If someone loads in some strange object where simply evaluating `foo.bar` might take an hour, they can turn off the eager evaluation, but most of the time that won't be necessary.
 
> However since most of the protection for (2) seems to have been removed by #1299, it's questionable why we still hold onto protection here (at least for `jedi.Interpreter` usages, which IPython uses).

Yes, I agree.  I can see somewhat more of an argument for "safety" if you're doing something like autocompletion within an IDE, where none of the code is being evaluated at all.  But in an interactive context, as I mentioned above, I don't think stopping the completion provides much protection: people can and will just manually evaluate the property anyway.

**Comment by fmagin** [comment]
Found this because this was related to my issue and something I ran into on various occasions: IMO in my opinion the general answer for cases like this should be: Use class variable annotations (I am not sure if Jedi parses them though, but I would consider this a relevant feature and help implement it)

I.e.:
```python
class CompleteAttrs(object):
    foo: 'CompleteAttrs'
    bar: int
    def __getattr__(self, name):
        if name == 'foo':
            # Used to be return 1
            return self
        if name == 'bar':
            # Used to be return 2
            return 1
        raise AttributeError(name)
    
    def __dir__(self):
        return ['foo', 'bar'] + object.__dir__(self)
```

For runtime completions this is exposed as:
```
In [7]: CompleteAttrs.__annotations__                                                                                                                                                                    
Out[7]: {'foo': 'CompleteAttrs', 'bar': int}
```
Something like `'CompleteAttrs'` (note the quotes) might be tricky because the unquoted version `CompleteAttrs` can't be used here because that type isn't defined yet. Just covering the cases where this is enough would be great already though.

Actually executing things can take long enough that it becomes annoying to use because typing the next few letters would still be faster than waiting for the autocompletion to generate the one possible result. Which is definitely a reason I and other people I know have turned off Jedi for.
