### ISSUE TITLE
consider scandir (instead of listdir) for filenames

### ISSUE THREAD

**Issue by Carreau** [davidhalter/jedi#1381]
Python 3.6+ has scandir (with [fallback on PyPI](https://pypi.org/project/scandir/) if not available) which should be significantly faster that listdir especially if you call is_dir or is_file.

**Comment by davidhalter** [comment]
Do you think the speed of listdir is actually an issue? Because I doubt it.

**Comment by Carreau** [comment]
Well on recent machine, maybe not, but on HPC, hard drive access can be
suuuuper slow. And the 'is_dir()' call will be extremely expensive but
basically free with scandir as they are collected at the same time.

I can try to test on a system I have access to to give you numbers.

**Comment by davidhalter** [comment]
Haha. I didn't think about this at all. I'm totally fine with replacing it. It's probably not the highest priority, but I'm happy to add that.

I'm against adding a dependency. I would probably just use it for 3.5+, because I'm going to stop supporting 2.7/3.4 soon anyway (a lot of "modern" features are not supported anymore). I would probably not even create a fallback. No file completions for Python 2 is probably the way to go then. So just in case you start implementing, don't worry about the older versions.

Just as a note for myself: https://github.com/ipython/ipython/blob/master/IPython/core/completer.py
