### ISSUE TITLE
Autocompletions not showing for decorated class methods

### ISSUE THREAD

**Issue by Rested** [davidhalter/jedi#1413]
Here is a minimal demo which hopefully explains why you might want to do this and what it is that isn't working. Any ideas why this is not working or any pointers of what to look into.
```python

from typing import Callable, TypeVar

Animal = TypeVar('Animal')

def decor(func: Callable[[Animal, int], None]) -> Callable[[Animal, int], Animal]:
    def inner(self: Animal, something: int) -> Animal:
        func(self, something)
        return self
    return inner

class Cat:
    @decor
    def meow(self, something: int) -> None:
        pass

class Dog:
    @decor
    def bark(self, something: int) -> None:#, *args: int, **kwargs:int) -> None:
        pass

reveal_type(Dog().bark(1)) # Dog*
reveal_type(Cat().meow(2)) # Cat*
Cat().meow(2). # gives abc 
```

**Comment by davidhalter** [comment]
I used `jedi.set_debug_function()` and it showed me: `warning: Tried to infer the TypeVar 'Animal' without a given type`.

This means that Animal as a type was never defined. Which is not your fault but Jedi's. The problem here is that TypeVar are not properly inferred for `Callable`. When it tries to look it up, it will not be defined. So what we have to do is this: Add another `if` in `jedi.inference.gradual.annotation._infer_type_vars`, a bit like this:

```
        elif name == 'Callable':
            given = annotation_value.get_generics()
            if given:
                # This should look like this: `Callable[[int, str], float]`.
                for nested_annotation_value in given[0]:
                    if nested_annotation_value.array_type == 'list':
                        for i, lazy_argument in enumerate(nested_annotation_value.py__iter__()):
                            _merge_type_var_dicts(
                                type_var_dict,
                                _infer_type_vars(
                                    nested_annotation_value,
                                    lazy_argument.infer().types_of_argument(i))
                                )
                            )
```

However note that the `types_of_argument` function does not exist yet, so there's obviously more work to be done (plus this code might be buggy anyways).

Note to myself: Maybe do it with `if is_function` and use something like unpack?

**Comment by Rested** [comment]
Ah okay, makes sense. I will have a play with the jedi code and see if I can get it working. Here is my actual use case which is a bit more complicated. I wonder if there is a way to solve both the same way? This may be a stupid question, but could mypy not be used for some of this?
```python
from typing import Callable, TypeVar, Protocol, Optional

FarmAnimal = TypeVar('FarmAnimal')

class DecoratedMethod(Protocol[FarmAnimal]):
    def __call__(self, __self: FarmAnimal, *args: int) -> Optional[FarmAnimal]: ...

def deco(func: DecoratedMethod[FarmAnimal]) -> Callable[..., FarmAnimal]:
    def inner(self: FarmAnimal, *args: int) -> FarmAnimal:
        func(self, *args)
        return self
    return inner

class Sheep:
    @deco
    def baa(self, *args: int) -> Sheep:
        return self

class Pig:
    @deco
    def oink(self, *args: int) -> None:
        return None

reveal_type(Sheep().baa(1)) # Sheep*
reveal_type(Pig().oink(2)) # Pig*
```

**Comment by davidhalter** [comment]
Yeah, this is something different, because the input is not `Callable`, but `Protocol`. I'm not really an export about protocols. Does this type check everything in mypy?

You cannot just use mypy. They are pretty much "competing" products.

**Comment by Rested** [comment]
Had a go at implementing, but it seems `_infer_type_vars` isn't called. 
```python
    source = dedent("""\
    from typing import TypeVar, Callable
    T = TypeVar('T')
    def ma(a: Callable[[str], T]) -> Callable[[str], T]:
        return a

    def mf(s: str) -> int:
        return int(s)

    ma(mf)('2').""")
    
    assert _remove_dunder([c.name for c in Script(source).completions()]) == _remove_dunder(dir(int))
```
also, is there a more direct way of testing this rather than using `.completions()`?

**Comment by davidhalter** [comment]
> Had a go at implementing, but it seems _infer_type_vars isn't called.

It was called. You can see that in the first commit above. 

> also, is there a more direct way of testing this rather than using .completions()?

There's multiple ways. If you want to do it with code, I typically use `script.goto_definitions()`, where you get back `int` in your case if you remove the dot. The other way is using the `test/completion` files. In there you can simply say something like `#? int()` before a statement to test if the next line is inferred as an `int` instance.

-----

I thought this was an easy fix in the beginning, but it turned out that stuff like `list[<type var>]` was programmed in a different way than `Callable[<type var>]`. So it was quite a hard task. A few of the more important commits are highlighted above. But it was like 25 commits when I last counted and it might be even more, because I'm still cleaning up stuff.

Anyway, I think it's good that I have done that.

**Comment by Rested** [comment]
Wow, that's a chunky bit of work! No problem, it was fun to have a play with a project i am a long time user of, and happy to see [my test made it in](https://github.com/davidhalter/jedi/blob/5acbb06315c5b1cd353604485f0ca0c7ba2bbeb3/test/completion/pep0484_typing.py#L405-L412). And would be happy to have a go at something more first-tickety, if something pops up feel free to @ me! Look forward to seeing this released 🚀

**Comment by davidhalter** [comment]
@Rested If you want, you can have a look at #516. It's not the most "interesting" ticket, but I wrote down the parts that are hard to understand. So if you're interested, please let me know and I will gladly help you with that one :).
