### ISSUE TITLE
overloads signatures

### ISSUE THREAD

**Issue by AmjadHD** [davidhalter/jedi#1417]
see https://github.com/palantir/python-language-server/issues/664 for more details
I have three files located in one folder:
mod.py:
```python
def add(x, y):
    return x + y
```
mod.pyi:
```python
from typing import overload


@overload
def add(x: int, y: int) -> int: ...


@overload
def add(x: int, y: float) -> float: ...
```
jedi does not provide all overloads signatures

**Comment by davidhalter** [comment]
I cannot reproduce. Not on master and also not on 0.15.1.

I added an additional test that makes sure this works. I feel like there's something different that's wrong in your environment, probably a sys path issue. Otherwise, please use `jedi.set_debug_function()` and let me know the output of that.

**Comment by AmjadHD** [comment]
I apologize, this has nothing to do with jedi, checking the source code, it turns out pyls only shows the first signature:
https://github.com/palantir/python-language-server/blob/48eedeaeff5f570d14e7845c12494e46649d3193/pyls/plugins/signature.py#L39
A simple info in the original issue would have spared us this.
