### ISSUE TITLE
Jedi showing system and home directory folders

### ISSUE THREAD

**Issue by Precrisk** [davidhalter/jedi#1446]
**OS: Arch Linux**
**Editor: Neovim**
**Code Completion: ncm2, ncm2-jedi**

**Expected Behavior:** 
after entering keyword `import` jedi will show modules from current project, standard library and system/virtualenv installed libraries. 

**Current Behavior:**
after entering keyword `import` jedi shows modules from all the sources listed above AND system directories like usr, dev, bin, etc, home, etc. and directories in home folder like Videos, Downloads, etc. 
there is no way to import these "modules" as these are not valid modules and even if these were modules these are not in `path`. 
and some 'modules' listed here like 'Calculator', 'Tasks', etc are valid python module but they are in different directory which i cannot import from my current project. 

Screenshots:
![Screenshot from 2019-11-25 08-48-26](https://user-images.githubusercontent.com/47627625/69512260-5decbc80-0f69-11ea-84a4-b1b795f64bda.png)
(this occurs even without `from home.precrisk.Python`)

**Comment by pappasam** [comment]
I have the same issue.

OS: Ubuntu 18.04
Editor: Neovim
Code Completion: deoplete + LanguageClient-neovim + jedi-language-server

**Comment by davidhalter** [comment]
Essentially the problem is that Jedi doesn't find a root for your Python project. Create a `setup.py`, `requirements.txt` or probably also an `__init__.py` somewhere to signal that it's a top level folder.

I'm happy to discuss improvements, but note that it's not easy, because we're trying to satisfy a lot of different stakeholders here :).

**Comment by ComputerHardman** [comment]
I have the same issue.

OS: Windows 10 (1809, 1803, 1709)
Editor: VSCode
Code Completion: jedi with the python extension

I have been able to replicate this with this code snippet 
```
import jedi
source = "import Pro"
script = jedi.Script(source, 1, len('import t'), 'example.py')
print(script)
completions = script.completions()
print(completions)
print(completions[0].complete)
```
the code snippet will show that folders like `Program Files (x86)` are suggested as completions.

**Comment by davidhalter** [comment]
If anyone has a better solution for this, please look at `_get_sys_path` in `jedi/api/project.py` and let me know. The logic is not that complicated. It is definitely intentional that a lot of sys paths are added, but this might be annoying for import completion. 

So in the end there's probably a balance we have to find to avoid issues like yours, but it's probably not avoidable that some unwanted folders are included.

**Comment by Precrisk** [comment]
I can understand that you need to hit the right balance, but i am not getting why you need to scan so many sys paths?

also, I already have requirements.txt in my root directory. 
My project structure is as follows:
/root directory/src/
                     /tests/
                    /.venv/
                    /.git/
                    /requirements.txt

and to start working i use commands as follows in my project root directory
```bash
source /.venv/bin/activate
nvim
``` 
and my nvim's `g:python3_host_program` is set to venv created specially for neovim that contains `pynvim`, `jedi`, etc.

I will try to play around `jedi/api/project.py` and see if i can get it working for me.

**Comment by davidhalter** [comment]
>  I already have requirements.txt in my root directory.

This might actually be a bug then.

**Comment by pappasam** [comment]
I confirm that overriding `jedi.api.project._get_sys_path` to simply return `sys.path` on Python 3.8 with a virtualenv activated solves the issue for me with a virtualenv activated. Therefore, as @davidhalter said, it's probably a bug.

**Comment by pappasam** [comment]
Also confirming now that the problem as to do with the `suffixed` array in `_get_sys_path`. By setting it to an empty array, the problem goes away. Will continue digging.

**Comment by pappasam** [comment]
Isolated to line 118: `suffixed += reversed(traversed)`

**Comment by davidhalter** [comment]
Thanks to @pappasam for looking into this.

**Comment by jdtsmith** [comment]
Reviving an old thread, but I notice that Jedi-completion in iPython is either reasonably fast, very slow or crashes outright depending on the depth of the current directory, for some packages.  Since iPython is interactive, that can change.  See ipython/ipython#13866.   I'm not sure why, once it has identified a package, completions of fields depends on the cwd.
