### ISSUE TITLE
Can't get signatures

### ISSUE THREAD

**Issue by bstaint** [davidhalter/jedi#1465]
Python 3.8.1, master branch.

testa.py
```
def testa_method(a, b, c):
    pass
```

1.py
```
import jedi
script = jedi.Script("from testa import *; testa_method(")
print(script.find_signatures())
```

output:
[]

**Comment by davidhalter** [comment]
WTF. How does Jedi pass all the tests without this working... Thanks for finding this!

**Comment by davidhalter** [comment]
Just realized that this is not really a bug, but more like a feature. The problem here is basically error recovery. `from testa import *; testa_method(` is not a valid statement. If you replace `;` with `\n`, it all works perfectly fine.

This could of course be improved, but since this is not how people write Python code in general, I'm just not going to "fix" it. In general this is usually how we do testing, but I really think that nobody writes code like that.

If you disagree let me know, but for now I'm closing.
