### ISSUE TITLE
How to analyze a folder with multiple python files?

### ISSUE THREAD

**Issue by WanCC1995** [davidhalter/jedi#1509]
I'm trying to apply static analysis on python projects, with contain multiple python files with dependency. I noticed that there's an API jedi.Script for analyzing a single file, but haven't found one for whole project. My current implementation is merging multiple files into one and then use this API. However, it's not scalable and incurs other related problems.
Is there anyway neat way to use Jedi analyze a whole project?

**Comment by davidhalter** [comment]
Have you tried the project branch? That API will be available in 0.17.0. You can just use `jedi.Project`.

Also what's your goal for analyzing? Some things are intentionally the way they are. You will have to recreate Script from time to time to avoid using a lot of memory (otherwise #1059 is still a very real problem).
