### ISSUE TITLE
Cached properties without triggering the cache?

### ISSUE THREAD

**Issue by tamasgal** [davidhalter/jedi#1518]
In a library I work on, we have several "heavy" properties which look something like this (dummy example):

```python
import time

class Foo:
    def __init__(self):
        self._bar = None
        self._baz = None

    @property
    def bar(self):
        if self._bar is None:
            time.sleep(5)
            self._bar = 23
        return self._bar

    @property
    def baz(self):
        if self._bar is None:
            time.sleep(5)
            self._baz = 23
        return self._baz

```

etc. (dozens of properties).

The problem is that creating an instance and hitting `TAB` will evaluate all the code inside the `if`-blocks since `Jedi` sees that the values are `None`, which means the REPL is hanging for several seconds (up to minutes).

```python
>>> from foo import Foo
>>> f = Foo()
>>> f.<TAB>    # hangs for a few seconds
```

Is there a way to e.g. tell Jedi beforehand about the signature of these properties to prevent this huge lag? I also tried using different implementations of `@cached_property` decorators but they have the same problems.

I also tried with type hints without success:

```python
class Foo:
    def __init__(self):
        self._bar = None
        self._baz = None

    @property
    def bar(self) -> int:
        if self._bar is None:
            time.sleep(5)
            self._bar = 23
        return self._bar

    @property
    def baz(self) -> int:
        if self._bar is None:
            time.sleep(5)
            self._baz = 23
        return self._baz
```

**Comment by davidhalter** [comment]
Thanks for the report.

This is unfortunately not really a bug but a "feature". I was against adding this, but most users wanted this kind of side effect.

There's still a hidden way to toggle this, which might be good enough for you. You can say

```
jedi.Interpreter._allow_descriptor_getattr_default = False
```

That should probably do the work. (No idea how you get that properly into an IPython session).

In fact I put in a ton of effort to avoid these kind of cases and a lot of people in the community complained that their properties weren't working anymore. See also this issue: https://github.com/davidhalter/jedi/issues/1299#issuecomment-520253660

PS: While I think you raise a valid point, I think it's an anti pattern to do a lot of calculations in properties. In general I think functions are better, because they allow you to "change" the functionality in the future while not breaking backwards compatibility. This has proven to be a big issue for Jedi in the past. So just a few thoughts (I know that's not always feasible to touch large code bases).

**Comment by krpatter-intc** [comment]
> jedi.Interpreter._allow_descriptor_getattr_default = False

Can we perhaps get this to be an official and non private setting?

**Comment by davidhalter** [comment]
Feel free to create a pull request with `allow_descriptor_getattr=True` for `Interpreter.__init__`. I will merge it.
