### ISSUE TITLE
goto() doesn't work on Types enclosed by quotes

### ISSUE THREAD

**Issue by davafons** [davidhalter/jedi#1521]
```python
import jedi

source = """
class Foo:
    def __init__(self):
        self.msg = "foo"

def fun(foo: "Foo"):   # line 6
    print(foo.msg)

def fun(foo: Foo):   # line 9
    print(foo.msg)
"""

script  = jedi.Script(source, path="test.py")
definitions = script.goto(line=6, column=16)
print(definitions)
definitions = script.goto(line=9, column=16)
print(definitions)
```
The output is:
```
[]
[<Definition full_name='test.Foo', description='class Foo'>]
```
But I think it should return the class definition in both cases, as "Foo" is being used as a type hint.

A deeper look at `parso` shows that the param type is treated as a string instead of being resolved to Foo class.
```python
import parso

module = parso.parse(source, version="3.6")
print(module.children[1].get_params())
print(module.children[2].get_params())
```
This prints:
```
[<Param: PythonNode(tfpdef, [<Name: foo@6,8>, <Operator: :>, <String: "Foo">])>]
[<Param: PythonNode(tfpdef, [<Name: foo@9.8>, <Operator: :>, <Name: Foo@9, 13>])>]
```
The conflicting code is here:

https://github.com/davidhalter/jedi/blob/8df917f1df9ff001b33b7ae91af2c4fc6c549011/jedi/api/__init__.py#L287-L293

`tree_name` is `None` because `get_name_of_position` treats "Foo" just as a string.

**Comment by davidhalter** [comment]
Thanks for the research!

However this is intentional. The types that are enclosed by quotes are recognized as strings and we deal with them that way. It would be possible to change this, but IMO it doesn't make sense, because this is going to change in Python 4.0: https://www.python.org/dev/peps/pep-0563/

You can also remove the quotes if you write `from __future__ import annotations` at the beginning of your file (Python 3.7+).

I hope you can understand. But I don't like to write code for this, when it's not going to be needed in the future. Feel free to create a pull request to "fix" this, I'm happy to merge it if it's well tested. However I won't work on this.

**Comment by davafons** [comment]
Hi! Thanks for your answer.

I get and share the point that this is not a relevant change given its not an issue anymore on Python 3.7+, but I still think it would be a little nice addition since using quotes is the only alternative on Python 3.6. I'll try to work on this!
