### ISSUE TITLE
SUBCLASSES AND METHOD OVERRIDES

### ISSUE THREAD

**Issue by shrhawk-entertainer** [davidhalter/jedi#1538]
Is it possible to find all the subclasses and method overrides using the library?

**Comment by davidhalter** [comment]
@shrhawk-entertainer Sorry, this is not supported. You could maybe do this with `get_references` for subclasses, but especially for method overrides there's nothing.

What do you want to use this for?

**Comment by shrhawk-entertainer** [comment]
https://github.com/microsoft/python-language-server/issues/1641
@davidhalter this will help to create an extension for vscode like above!

any example for finding subclasses using `get_references`?

**Comment by davidhalter** [comment]
Use get_references and then play a bit with the API output (like get the code lines and check if `class ` is in there). That's probably not 100% correct, but it should work most of the time.

I'm closing this one here, since I don't intend on implementing this.

If somebody wants to implement this, let's talk about it, but you have to do the work.
