### ISSUE TITLE
Compiling jedi with cython?

### ISSUE THREAD

**Issue by laurentS** [davidhalter/jedi#1634]
Hi all,
This is more a question than a bug report. Like many others, I've been waiting for those precious (milli)seconds while jedi is parsing a big library to deliver its magic (and I really love the magic of it!). I've looked at a few other tickets here about the issue, including #1059 and I was wondering if anyone has ever tried to compile jedi with cython.
I've not used cython for anything besides the demo tutorial, so I might be missing some key info, which is partly why I'm opening this ticket. But I get the impression that there is potential for some significant speedups.

Has anyone ever tried it?
Are there any obvious blocking points that would make it impossible, or not worth the effort?

I was tempted to give it a try, but thought it would probably make sense to check here first.

In any case, thanks for the awesome tool!

**Comment by FFY00** [comment]
Other option is to put type hints internally everywhere and use mypyc.

**Comment by davidhalter** [comment]
> Has anyone ever tried it?

Probably not, it's just typically not worth porting things to Cython without adding type information. It might be worth in some very specific scenarios. But Jedi uses a lot of dict lookups which are hard to optimize. I might also be wrong, because it has been a while since I've used Cython. I had higher hopes for pypy, but that also doesn't really help unfortunately :(.

> I was tempted to give it a try, but thought it would probably make sense to check here first.

Makes sense. Feel free to try it and report back. I might close this issue after a while, because it's not really an issue. But I would be very interested in the results.

> In any case, thanks for the awesome tool!

Glad you like it :).

**Comment by laurentS** [comment]
Thanks for the helpful comments @davidhalter I'll close this now, but will report back when I get a moment to try it.

**Comment by davidhalter** [comment]
Great! Thanks for looking into this. I'm really interested in the results. So please make sure to post here :).
