### ISSUE TITLE
Jedi support for custom importers?

### ISSUE THREAD

**Issue by storm-lord** [davidhalter/jedi#1672]
First off, thank you for this amazing library!

I work with a custom importer that handles non-standard loading (reading/executing) of modules. That being said, I would like to use that same importer through Jedi's API. The only existing topic that I found is this [issue](https://github.com/davidhalter/jedi/issues/452).

The issue was closed in 2016 with the statement that there are no plans to support this kind of behaviour. So my question is, 4 years later, was there any change of plans regarding this topic?

Thanks!

**Comment by davidhalter** [comment]
No. I don't plan on doing that. It's just too much work for people that work mostly in enterprises. I also think that such import handling is usually a bad idea and should therefore not be supported.

So unless a company is willing to pay a lot of money for this, I'm not going to implement it (or merge it, because of the maintenance burden).
