### ISSUE TITLE
Unable to autocomplete on chained functions with numpydoc 

### ISSUE THREAD

**Issue by xinrong-databricks** [davidhalter/jedi#1686]
The `groupby` function in Koalas library had no return type annotation, but had a docstring in `numpydoc` format with return type specified.

In bpython:

Not able to autocomplete when chaining functions:
![image](https://user-images.githubusercontent.com/47337188/96750785-38d31a80-1381-11eb-9a69-e6d3285e779b.png)

Able to autocomplete as below:
![image](https://user-images.githubusercontent.com/47337188/96751064-99625780-1381-11eb-9a27-299a29cc6602.png)

May I ask if this is a known issue?

**Comment by davidhalter** [comment]
It is basically a known issue. If you want you can dive into the code and try to improve it. However if I were you I would rather try to impove the type annotations for that specific library. Type annotations are the future and type docstrings (like numypdoc types) are basically just an old relict.

I'm going to close, because it's pretty much expected that numpydocs completions don't work in more complex cases. However feel free to continue the discussion.

If you show me the numpydoc docstring that is responsible, I can probably tell you why it's not working.
