### ISSUE TITLE
pytest integration tests fail on Python 3.9 and they are skipped on CI

### ISSUE THREAD

**Issue by hexchain** [davidhalter/jedi#1699]
In the current master branch, the pytest integration tests fail to run on Python 3.9 (logs: http://ix.io/2Fcd) and they are skipped on CI.

I have a fork with some changes to simplify the test matrix and to increase the verbosity of pytest (difference [here](https://github.com/davidhalter/jedi/compare/master...hexchain:master)), and [this](https://travis-ci.org/github/hexchain/jedi/jobs/745396872) is the result on Travis CI. If you search for "[pytest:28]" in the log, you can see that all `test_completion[pytest:*]` are skipped.

**Comment by davidhalter** [comment]
So what are you telling me?

**Comment by hexchain** [comment]
1. These tests fail on Python 3.9;
2. They are skipped in the CI, which I think they shouldn't.

**Comment by davidhalter** [comment]
1. I unfortunately know already. I have tried to enable them before.
2. It's just that nobody ever wanted to invest into that testing system, because debugging it is just tedious work. I likely won't do it, it's simply not worth it. Especially not when everybody is moving to GitHub actions. GitHub actions would probably be the first step.

**Comment by hexchain** [comment]
Thanks for the response. It sounds like this is not actionable anyway, at least not before moving to another CI.

I'm closing this for now.

**Comment by davidhalter** [comment]
Fixed in https://github.com/davidhalter/jedi/pull/1715.
