### ISSUE TITLE
Various parso objects being referenced after request for completions

### ISSUE THREAD

**Issue by CJ-Wright** [davidhalter/jedi#1723]
It seems that there are some parso objects being referenced somewhere and not being released. This seems to cause some memory leak like effects on my machine.

Example code:

```python
import jedi
from pympler import tracker

tr = tracker.SummaryTracker()
jedi.Script(path='path/to/simple/code.py').complete()
tr.print_diff()
```

My expectation was that once the completion had finished running (and since it didn't put the list into a variable is slated for garbage collection) then all the jedi/parso objects would be cleaned up. Is this not the case? What is the best way to clean up all the jedi/parso objects?

For some context I'm currently running jobs that extract completions from many different codebases so the size of the objects really starts to pile up.

**Comment by davidhalter** [comment]
Jedi is primarily used for end user stuff where caching is vital. Objects are cached and  cleaned up at some point (like a LRU cache), but that might take a while.

Why is it an issue if Jedi uses 500 MB of RAM? Also what are you trying to accomplish?

In general I'm inclined to close, because other than commercial applications I just don't see the open source community really needing something like this with what Jedi currently is. But maybe you can explain why this makes sense for you.

You can obviously dig into the code and delete the caches, but don't delete everything, because deleting all the typeshed/stdlib caches will make Jedi really slow.

**Comment by CJ-Wright** [comment]
The issue is that it isn't using 500 MB of ram but in excess of 1.3 GB of ram (or more, it seems to take as much ram as available).

I am currently using Jedi to collect all the symbols shipped by conda-forge [here](https://github.com/symbol-management/cf-symbol-table). This information could be used for various goals, including determining which versions of a package support a particular API, determining if two versions of a package are mutually compatible, helping downstream code maintainers to determine what changes are needed to use new codebases, among others.

**Comment by davidhalter** [comment]
Alright. That sounds like a reasonable thing to do.

I'm currently not interested in a public API, but it's not that hard to delete the objects yourself. It's a "private" part, but you can probably do this (it might break in some future release):

```
from parso import cache
cache.clear_cache()
```

For performance reasons, I wouldn't do this after every library analyzed. It's still pretty bad, because it also invalidates caches that should not be invalidated like `builtins`, but if you don't call that function to often it's probably not a big problem.

**Comment by CJ-Wright** [comment]
I can't use `parso.cache.clear_cache()` since there is no file on disk and I get a `FileNotFound` error.

I did try `jedi.cache.clear_time_caches(True)` to try to clear the caches (I think that clears the `parso.cache.parser_cache`) but there still seem to be objects left in memory.

Running 
```python
import jedi
from pympler import tracker
from jedi import cache

tr = tracker.SummaryTracker()
jedi.Script(path='/path/to/code.py').complete()
cache.clear_time_caches(True)
tr.print_diff()
```

Yields:

```
                                types |   # objects |   total size
===================================== | =========== | ============
                                 list |       39543 |      3.90 MB
                                  str |       38928 |      2.23 MB
           parso.python.tree.Operator |       26324 |      2.21 MB
                                 dict |       14046 |      2.04 MB
               parso.python.tree.Name |       17904 |      1.23 MB
                                  int |       40110 |      1.07 MB
         parso.python.tree.PythonNode |       18789 |      1.00 MB
            parso.python.tree.Keyword |        3993 |    343.15 KB
            parso.python.tree.Newline |        4796 |    337.22 KB
                                  set |         817 |    255.84 KB
        parso.pgen2.generator.DFAPlan |        5411 |    253.64 KB
              parso.python.tree.Param |        3479 |    217.44 KB
    parso.pgen2.grammar_parser.NFAArc |        2745 |    128.67 KB
  parso.pgen2.grammar_parser.NFAState |        2390 |    112.03 KB
           parso.python.tree.Function |        1681 |    105.06 KB
```

should `clear_time_caches` remove all the parso objects from memory? Are they being cached anywhere else?

**Comment by davidhalter** [comment]
I think I got it wrong. you probably have to use `parso.cache.parser_cache.clear()`.

`clear_time_caches` is really something I wouldn't use. It's not used a lot (I think only for signatures and environments, and at least the latter is something you do not want to lose).

**Comment by CJ-Wright** [comment]
Running this:
```python
import jedi
from pympler import tracker
import parso.cache

tr = tracker.SummaryTracker()
jedi.Script(path='/home/cjwright/dev/depfinder/depfinder/inspection.py').complete()
# tr.print_diff()
parso.cache.parser_cache.clear()
tr.print_diff()
```

Yielded:
```
                                types |   # objects |   total size
===================================== | =========== | ============
                                 list |       39543 |      3.90 MB
                                  str |       38928 |      2.23 MB
           parso.python.tree.Operator |       26324 |      2.21 MB
                                 dict |       14046 |      2.04 MB
               parso.python.tree.Name |       17904 |      1.23 MB
                                  int |       40110 |      1.07 MB
         parso.python.tree.PythonNode |       18789 |      1.00 MB
            parso.python.tree.Keyword |        3993 |    343.15 KB
            parso.python.tree.Newline |        4796 |    337.22 KB
                                  set |         817 |    255.84 KB
        parso.pgen2.generator.DFAPlan |        5411 |    253.64 KB
              parso.python.tree.Param |        3479 |    217.44 KB
    parso.pgen2.grammar_parser.NFAArc |        2745 |    128.67 KB
  parso.pgen2.grammar_parser.NFAState |        2390 |    112.03 KB
           parso.python.tree.Function |        1681 |    105.06 KB
```

Is it possible that the information is also cached somewhere else?

**Comment by davidhalter** [comment]
Can you try to run `gc.collect()` after `parser_cache.clear()`?

**Comment by CJ-Wright** [comment]
```python
import jedi
from pympler import tracker
import parso.cache
import gc

tr = tracker.SummaryTracker()
jedi.Script(path='/home/cjwright/dev/depfinder/depfinder/inspection.py').complete()
# tr.print_diff()
parso.cache.parser_cache.clear()
gc.collect()
tr.print_diff()
```

```
                                types |   # objects |   total size
===================================== | =========== | ============
                                 list |       39543 |      3.90 MB
                                  str |       38928 |      2.23 MB
           parso.python.tree.Operator |       26324 |      2.21 MB
                                 dict |       14046 |      2.04 MB
               parso.python.tree.Name |       17904 |      1.23 MB
                                  int |       40110 |      1.07 MB
         parso.python.tree.PythonNode |       18789 |      1.00 MB
            parso.python.tree.Keyword |        3993 |    343.15 KB
            parso.python.tree.Newline |        4796 |    337.22 KB
                                  set |         817 |    255.84 KB
        parso.pgen2.generator.DFAPlan |        5411 |    253.64 KB
              parso.python.tree.Param |        3479 |    217.44 KB
    parso.pgen2.grammar_parser.NFAArc |        2745 |    128.67 KB
  parso.pgen2.grammar_parser.NFAState |        2390 |    112.03 KB
           parso.python.tree.Function |        1681 |    105.06 KB
```

**Comment by davidhalter** [comment]
Realized that this is actually an issue. `WeakKeyDictionary` does not work like I thought it would. After thinking about it, it makes sense. But I'm not sure how easy a fix would be.

You could probably just use this instead:

```
parso.cache.parser_cache.clear()                                              
jedi.inference.filters._definition_name_cache.clear()                         
jedi.parser_utils.get_cached_parent_scope.__closure__[0].cell_contents.clear()
```

Of course this can change from commit to commit, but if you pin the release it would probably work.

**Comment by davidhalter** [comment]
This was pretty hard to fix. Of course there's still no way to properly control caches. This would require a proper parso refactoring. Feel free to do that. However I feel like this shouldn't be that important. `parso.cache.parser_cache.clear()` should suffice with the latest changes.

Of course this once again shows that the caching in parso is pretty much not good enough for Jedi. Jedi should probably ignore parso's caches and use its own. But that's a lot of work that I'm not willing to invest right now.

@PeterJCLaw I intentionally did not create a PR for this, since this requires a lot of knowledge about the parso caches and I feel like the fix is quite ugly and not really worth a second look. However I really felt like it was necessary, because this is really a memory leak in Jedi that might cause problems for users running Jedi for a long time. I really really don't like how this ended up, but I have tried a few other approaches and it just didn't work, because I don't want weakrefs in parso's tree, because that would mean a significant memory overhead (parso is using `__slots__` for all of it's nodes/leaves).

**Comment by CJ-Wright** [comment]
Thank you for your work on this!!
