### ISSUE TITLE
Show auto-completion items together with their src path

### ISSUE THREAD

**Issue by Alexey-T** [davidhalter/jedi#1728]
VSCode can now show autocompletion items with additional string: path of source file.

>TypeScript can provide completions that also add an import statement. However, when there are multiple symbols with the same name, it is hard to pick the right completion. This release makes this simpler because paths of auto-import completions are shown with the label.

<img width="642" alt="vs-path" src="https://user-images.githubusercontent.com/4154978/104091682-e0306100-528f-11eb-8fd0-857e520013b2.png">

additional string is of gray font color.
how Jedi can help? to do the same.

@kvichans @OlehL for your info.

**Comment by OlehL** [comment]
It can be useful for TypeScript/JavaScript. But for Python and many other languages can't be multiple symbols with the same name.

**Comment by PeterJCLaw** [comment]
In Python there cannot be more than one symbol with a given name _in scope at a time_. My guess is that what VSCode is doing here for JavaScript is showing symbols which are not yet imported and that when one was selected the proper import statement would also be added.

If that is the case, then this feature is actually quite different -- what would really be wanted here is a way to show the symbols which match a given name and are present anywhere in the Python environment, rather than those in the scope of the current file. Jedi currently focusses on the latter.

**Comment by davidhalter** [comment]
Something like `list(jedi.get_default_project().search('Project'))` could help.

However Jedi currently has no intentions to search diffferent files for random symbols. Jedi would just be too slow for that. So I'm closing, because without a cache this is just not feasible. Not that it would be hard to implement, but it's just way too slow for medium/large projects.

**Comment by davidhalter** [comment]
If we ever have a solution for https://github.com/davidhalter/jedi/issues/1059, I think we can improve some things in the direction you want, but since I doubt that that will ever be the case, closing makes more sense.
