### ISSUE TITLE
Add a Code Of Conduct

### ISSUE THREAD

**Issue by webknjaz** [davidhalter/jedi#1737]
Hi @davidhalter! I hope you're doing well these days. I was looking at an issue relating to the recent ipython incompatibility and couldn't help but notice that the behavior of certain individuals was rather unfriendly and disrespectful. This made me sad and I saw that there's no CoC set up in this project.

I think it may be a good idea to add one, here are some reasons why it may be helpful: https://opensource.guide/code-of-conduct/.

If you decide to proceed and add a CoC, it's quite easy to do:
1. Go to https://github.com/davidhalter/jedi/community
2. Click the `Propose` button on the line that says `Code of conduct`
3. Select `Contributor Covenant` and commit it
4. You can make changes to it later if you feel like something needs to be clarified

Have a nice day!

P.S. Of course, it's totally your decision whether to add a CoC, I just wanted to raise this in the open.

**Comment by davidhalter** [comment]
@webknjaz Thanks for bringing it up. I don't think CoCs help with "trolls" or in general random people that are not nice. If they help with anything it's with aligning the contributors. And since the regular contributors are only me and @PeterJCLaw I don't really see the benefit.

However if the amount of regular contributors grows, I'm willing to have that discussion again.

In the meantime I should probably just cite the MIT license: 

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND

:)

**Comment by webknjaz** [comment]
> I don't think CoCs help with "trolls" or in general random people that are not nice. If they help with anything it's with aligning the contributors.

From my experience, something should guide people regardless if they contribute code. Having community discussions is also a contribution of some knowledge. A CoC is supposed to cover any interactions in the community, regardless of whether they happen on GitHub or elsewhere.
In general, it's often nice to have something to point at when people are way out of line. And you can justify banning the offenders when the interaction is overly bad. It's perceived differently by the community. Think about it "a grumpy maintainer told somebody to go away" vs "a maintainer upholds high standards of respectful interactions".

> > THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND

Agreed :) After reading that thread I wanted to bring it up but then realized that this would cause an unnecessary reply-storm.

**Comment by davidhalter** [comment]
> Think about it "a grumpy maintainer told somebody to go away" vs "a maintainer upholds high standards of respectful interactions".

That's probably where we differ: I would like to be seen for what I am. I am a grumpy maintainer sometimes. That's just how it is. I don't see myself as upholding any standards. I'm just as annoying as everybody else, haha. That's why I'm probably fine with them nagging a bit.

I just don't think they get how hard it is to work on bigger open source projects. That's not evil - it's just ignorant. In general Jedi is a very quiet place, we probably have it like once a year where somebody does not understand what they are entitled to.
