### ISSUE TITLE
Jedi is unable to complete import statements for zip-modules

### ISSUE THREAD

**Issue by KRE02** [davidhalter/jedi#1771]
Jedi gives no completion for imports of modules that are zip files.

Example (there is a module mymodule.zip in `sys.path`):
```python
import jedi
print(jedi.Script('import mymo').complete())
```
Trying to complete `import <symbol> from mymodule` doesn't work either.

jedi version: 0.18.0

**Comment by davidhalter** [comment]
If you are interested in getting it working, please patch `inference/compiled/subprocess/functions.py`. There is probably one or two other places you need to touch.

However note that I don't consider this important and I won't do it since it hasn't been an issue for a lot of users. So if you are going to work on it I will keep the issue open, otherwise I will close it.

**Comment by KRE02** [comment]
Thank you, we will look into this next week, so please keep the issue open.
