### ISSUE TITLE
Support for dynamically created classes / types - mention in docs under "Limitations"?

### ISSUE THREAD

**Issue by smheidrich** [davidhalter/jedi#1792]
It seems that currently dynamically created classes (using the builtin `type()`) that subclass another class are not understood, with methods on the subclass not showing the signature of that on the superclass. Running e.g. the example code

```python
class A:
  def a_meth(self, x=None, y=None):
    "docstring for A.a_meth"
    print("a_meth")

B = type("B", (A,), {})

a = A()
b = B()

a.a_meth()
b.a_meth()
```

through

```python
from jedi import Script

with open("example.py") as f:
  scr = Script(f.read())

for obj_name, line in [("a", 11), ("b", 12)]:
  print(f"{obj_name}:")

  sigs = scr.get_signatures(line, 9)
  for sig in sigs:
    print(sig.to_string())
```

yields the output:

```
a:
a_meth(x=None, y=None)
b:
```

Are there plans to support this in the future? And could it be mentioned under [Limitations](https://jedi.readthedocs.io/en/latest/docs/features.html#limitations) in the docs in the meantime?

**Comment by davidhalter** [comment]
There are no plans to support this. If you want to mention it in the limitations please create a PR.

Otherwise I'm going to close this issue. I think that using `type` with three arguments is almost always a bad idea. However, in your example people could just get completions by using `B: A = type("B", (A,), {})` as a workaround.

**Comment by smheidrich** [comment]
OK thanks for the reply! :+1:
