### ISSUE TITLE
Exception - python 3.8.6 mac os catalina

### ISSUE THREAD

**Issue by ganatraad** [davidhalter/jedi#1814]
`  File "/Users/aganatra/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/value/module.py", line 176, in py__file__
    return self._path.absolute()
AttributeError: 'str' object has no attribute 'absolute'
`

It seems that [this line](https://github.com/davidhalter/jedi/blob/bb5bed49370ae6b5309f38cf49df6850e3677eb3/jedi/inference/compiled/subprocess/functions.py#L185) is setting module path to be a string

I am at commit bb5bed49370ae6b5309f38cf49df6850e3677eb3

**Comment by davidhalter** [comment]
It seems like something loads the module without it being a `Path`, but I'd have to investigate.

**Comment by ganatraad** [comment]
Thanks, I tried the trivial fix of making the module path a Path, but that
caused something in parso to throw in some other context. Definitely harder
than the one liners I can bring to the table.

**Comment by davidhalter** [comment]
It is probably a one liner that you can bring to the table, the question is just how hard you search for it :).

Just in general the module system definitely works and `py__file__` is probably called quite a bit. Also the annotations in `Module` show that `self._path` should be a `Path` object. So you can simply `assert isinstance(self._path, Path)` in `__init__` and I'm pretty sure you will find the culprit. Otherwise you can maybe just show us how you can reproduce this.

**Comment by ganatraad** [comment]
Ok, I will take  your pointers  and try  to find  that one line.
The situation I am in might be  a bit abstruse, there  is  a double  nested
namespace  package that I have  installed in editable mode. If I can't get
to the bottom of this I will try to create the simplest situation where
this  shows  up.

**Comment by ganatraad** [comment]
parso was not at the latest commit, my bad
