### ISSUE TITLE
Question: about Jedi magical definition

### ISSUE THREAD

**Issue by ericsia** [davidhalter/jedi#1838]
May I know the magic behind how jedi retrieve the definition?
I mean where is it store, because I like to add additional text or simplify some.
![image](https://user-images.githubusercontent.com/24624808/154836188-c0462e07-1e1f-474a-bb05-4b4737848bf4.png)

**Comment by PeterJCLaw** [comment]
The information you see is generally pulled from the docstring of the relevant object:
``` python
def func():
    """This text will appear in editor tooling and other help contexts"""
```
This is also the case for things in the standard library, even though the source code may not necessarily be in Python.

For example, you can see the same text returned by the built-in `help` function:
``` python
>>> help(bytearray)
```
```
Help on class bytearray in module builtins:

class bytearray(object)
 |  bytearray(iterable_of_ints) -> bytearray
 |  bytearray(string, encoding[, errors]) -> bytearray
 |  bytearray(bytes_or_buffer) -> mutable copy of bytes_or_buffer
 |  bytearray(int) -> bytes array of size given by the parameter initialized with null bytes
 |  bytearray() -> empty bytes array
 |  
 |  Construct a mutable bytearray object from:
 |    - an iterable yielding integers in range(256)
 |    - a text string encoded using the specified encoding
 |    - a bytes or a buffer object
 |    - any object implementing the buffer API.
 |    - an integer
 |  
```

So depending on what text it is you want to improve, the changes will need to be made in the source code for that function/class/whatever, rather than in jedi.

**Comment by ericsia** [comment]
I see~ now I can sleep peacefully
