### ISSUE TITLE
Can I get a call stack for a variable? 

### ISSUE THREAD

**Issue by richtier** [davidhalter/jedi#1854]
Hello :) Very cool tool.

I would like to determine all the places a variable is passed to, practically I mean:

```py
def a(x):
    return x.format(bar=1')

def b(y):
    value = 'hello {bar}'
    return a(value)
```
How to see all the places `__main__.b.value` was used? Making the list manually I see it's used on line 5, 6, and 2:

```py
value = 'hello {bar}'  # stored
a(value)  #  accessed
x.format(bar=1')  # passed into function a and then accessed
```

I have tried `get_refernces` but it does not follow the variable to `a`, so I think I'm misunderstanding what that function does:

```pt
In [2]: script = jedi.Script("""
   ...: def a(x):
   ...:     return x.format(bar=1')
   ...: 
   ...: def b(y):
   ...:     value = 'hello {bar}'
   ...:     return a(value)
   ...: """)

In [3]: script.get_references(6, 4)
Out[3]: 
[<Name full_name='__main__.b.value', description="value = 'hello {bar}'">,
 <Name full_name='__main__.b.value', description='value'>]
```

Is what I am asking possible?

**Comment by davidhalter** [comment]
`get_references` calculates the places where a name is used.

I feel like it's a bit weird to follow the params in different functions. What's are your goals?

**Comment by richtier** [comment]
Thanks for the explanation :)

My goal is to see all the places a given string is used so I can see the methods that were called on that particular string.

That's "easy" to do if the string is only used in the function scope it was defined in. That can be done via simple ast library using a visitor. My problem is I'm having trouble finding a static analysis tool that statically "follows" a variable around the codebase as it's passed as arguments into other functions or returned by a function.

**Comment by davidhalter** [comment]
This will not be supported in Jedi, for simple performance reasons. It's just extremely slow with the current design.

Most static analysis tools choose not to do this, because it gets endlessly complicated and you cannot guarantee anyway that you caught everything. Jedi tries its best with `get_references` on methods as well, but I'm pretty sure it has its limits as well. You could try calling `get_references` on all the methods you want to check.

#1059 might eventually help.
