### ISSUE TITLE
question: is PEP 701 going to be a problem for jedi ? 

### ISSUE THREAD

**Issue by stonebig** [davidhalter/jedi#1901]
I'm thinking about that specific one 

https://discuss.python.org/t/pep-701-syntactic-formalization-of-f-strings/22046/24

![image](https://user-images.githubusercontent.com/4312421/209827654-50680c1c-a46e-47b2-bdc2-02adc30404ba.png)

**Comment by davidhalter** [comment]
Thanks for coming by and asking me about this.

It won't be a problem at all, since this is what we're already doing. It might be bugged, because we haven't tested it, but the basic functionality should be there. In fact I offered years ago to implement it like this in CPython: https://github.com/python/cpython/issues/77935
