### ISSUE TITLE
sys.setrecursionlimit(3000) can cause stack overflows on Windows

### ISSUE THREAD

**Issue by pfox89** [davidhalter/jedi#1902]
The sys.setrecursionlimit(3000) call in `api/__init__.py` can cause stack overflows on Windows, as this limit can exceed the default Windows stack size under some conditions.

Either this should be done on a more targeted section of code and reset afterwards, or another way to avoid hitting the default recursion limit should be used. I'm not sure where this is actually needed for jedi, though.

Please see dask/dask#9805 for an example of this issue.

**Comment by davidhalter** [comment]
I commented there. I agree that this is problematic and should probably be used like a decorator when calling Jedi code.

There are two problems:

- It's hard to catch all (or even most cases) where Jedi type inference is called, because there's a lot of different cases.
- I'm not sure how fast setting the recursion limit is. So if this might cause performance headaches that I'm not sure I'm willing to trade for, because this is an extremely rare issue. This issue has existed for years. Jedi has been enabled by default in IPython for years. Millions of users have not spotted this one. This is definitely annoying, but it's also a kind of niche issue that most people will (even on Windows) never experience.

The reason for the recursion limit is that Jedi uses itself a lot of recursion and the default recursion limit is just not high enough for Jedi. It's also not very high when you consider how many functions you could typically call in C on an 8MB stack (and we're not even talking about tail recursions). However recursion is also an architectural issue in Jedi that's really hard to fix now. I know that this can cause stack overflows on Linux even with Jedi as well, but it's an extremely rare case compared to how many `RecursionError` there were before.

**Comment by pfox89** [comment]
So, one thing that's worth noting is that it looks like the recursion limit is per-thread (see https://github.com/python/cpython/blob/main/Python/sysmodule.c)

Although on Windows it is not easy to change the main thread stack (it's set by the exe header, so can only be changed at link time), setting the stack size for other threads is fairly easy using the `threading` library.

One potential solution for instances where the default stack and recursion limit are too small is to run jedi in a separate thread with a larger stack and recursion limit. This also the effect of completely isolating the effects of the recursion limit being set.

Now, I'm not sure this is something that is reasonable to implement in Jedi itself, but maybe it's something users of Jedi (like IPython), could do?

**Comment by davidhalter** [comment]
> If performance is really a major concern, then maybe the best approach would be to look for low-hanging fruit in Jedi in terms of reducing the use of recursive expressions. If there are tail-calling functions, for example, a tail-call optimizing decorator could be used to unwind the recursion with minimal code changes (https://pypi.org/project/tail-recursive/).

It's unfortunately not that easy. the problem in general is that type inference is inherently recursive (if you do it lazy), which combined with a few architectural issues leads to massive issues.

Also there was already a ton of performance optimizing done in the past (like multiple full days of work), so it's not like this is easy.

However since @Carreau mentioned that it takes only a few ns to change the recursion limit, we could probably just do that upon calling Jedi (and reset it when we leave Jedi code). It's probably good enough in a first iteration to just write a decorator that wraps all `Script` and `Project` functions.

**Comment by pfox89** [comment]
I guess all the low-hanging fruit has already been addressed, then.

Setting the recursion limit should be pretty fast, and it's per-thread, so it shouldn't cause issues with other threads, so that should be fine as first-order solution.

My thought was that if the recursion limit needs to be expanded, there is still a risk that Jedi could overflow the stack on Windows, depending on how it's used. If this does become an issue, it might be a good idea to recommend that users use `threading.stack_size()` and run the analysis code using Jedi in a separate thread so a larger stack can be reserved to avoid overflows.

**Comment by davidhalter** [comment]
> My thought was that if the recursion limit needs to be expanded, there is still a risk that Jedi could overflow the stack on Windows, depending on how it's used.

There's also a risk of this on Linux. This has happened on Linux before. The thing is just that this doesn't really matter. I know that there are recursion issues and whether somebody posts a bug as a stack overflow or with the proper Python stack trace doesn't really matter to me.

The thing we are trying to fix is not Jedi, it is the fact that arbitrary software runs next to Jedi in the same Python process. This software then instead of seeing RecursionError would just see an unexpected stack overflow.

**Comment by pfox89** [comment]
That makes sense, I agree.

My suggestion is that a note be made in the Jedi documentation about the expanded recursion limit and what adjustments the user might want to make to how they use Jedi if they're going to rely on being able to handle recursion limit exceptions (run any analysis using Jedi in a separate thread with an expanded stack size), but ultimately you'd know better than I whether that's a useful addition to the documentation or not.

**Comment by davidhalter** [comment]
I will close this issue in favor of #1925. The stack overflows are not really bothering me more than RecursionErrors, but it is definitely wrong for Jedi to just set this limit globally.
