### ISSUE TITLE
Code completion looses Self return type if method is wrapped with type hinted decorator

### ISSUE THREAD

**Issue by binste** [davidhalter/jedi#1919]
The issue came up in [this PR in the Altair repo](https://github.com/altair-viz/altair/pull/2920) were we are trying to improve autocompletion for IDEs such as VS Code as well as Jupyter with installed JupyterLSP and python-lsp-server. The approach suggested in the PR works for VS Code but not for JupyterLSP. Let me know if this is not a Jedi but a python-lsp-server or jupyterlsp issue.

As a large part of the codebase of Altair is auto-generated, the current approach relies on some type hinted decorators. The actual decorator we use is more complex but I tried to reduce it to a minimal reproducible example below. I'm running this on Python 3.9 with newest Jupyterlab, Jupyterlsp, and python-lsp-server[all]:

```python
from typing import Callable
from typing_extensions import Self

def use_signature(Obj):
    def decorate(f: Callable):
        return f
    return decorate

class SignatureClass:
    def __init__(self, arg1, arg2):
        self.arg1 = arg1

class MainClass:
    @use_signature(SignatureClass)
    def returns_self(self, *args, **kwargs) -> Self:
        return self
    
    def another_method(self):
        pass
```

`return_self` correctly shows `Self` as return type:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/23366411/221275941-dae6d18d-ab30-4f8b-941d-8a569771e769.png">
 but it cannot complete `another_method`

<img width="436" alt="image" src="https://user-images.githubusercontent.com/23366411/221276037-5b6cbb3d-11a7-4686-a3d0-e4008b6253c8.png">

When removing `Callable` from the `decorate` function it still shows `Self` as return type and can now complete `another_method`:

<img width="776" alt="image" src="https://user-images.githubusercontent.com/23366411/221276227-55bad52d-7568-4797-9e97-97fd03816f24.png">

The expected behaviour would be that `another_method` can be completed even with the `Callable` annotation, especially as it still is aware of the return type hint `Self`.

**Comment by davidhalter** [comment]
Self is currently not supported.

**Comment by PeterJCLaw** [comment]
I'm not sure that this relates to the use of `Self`. What happens if the code is modified so the return annotation is e.g: `int` rather than `Self`?

I think the issue you're hitting could be related to your decorator having an imprecise annotation and that causing a loss of information. I expect that you'll see similar results with a type checker too. `Callable` (without generic arguments) expands to `Callable[..., Any]`. The type of `f` in your decorator is thus `Callable[..., Any]`, which accepts a function which returns anything but also then erases the related type information.

Due to the lack of return type annotation on your decorator function, I think that Jedi is inferring the type from `f` there -- which is the erased type and not the specific type from your callsite. When removing that annotation however, Jedi instead infers that the input type should be passed through unchanged (equivalent to using a generic typevar as the type of `f`, such as `def foo(f: T) -> T`), which is why this then works in that case.

It is not clear to me that Jedi ignoring the type annotations (incomplete as they are) would be an improvement, especially when a more precise or complete type annotation would resolve the issue both in terms of editor completions and correctness.

I would suggest trying (have not tested myself) one of the following for your decorator:
* using `TCallable = typing.TypeVar('TCallable', bound=Callable[..., typing.Any])` as the type of `f`; for the code as presented the right thing would be to annotate the return as this too, though from your description I suspect this won't be right for your actual use-case; I suspect you may need to use `TCallable` as part of the annotation to `use_signature` and then as the return type from the `decorator` function in your use-case, but again haven't tried this at all
* using `typing.ParamSpec`, which is going to get you closer to the right semantics and thus (once Jedi supports it; see #1812) more correct completions

**Comment by davidhalter** [comment]
Thanks @PeterJCLaw 

I didn't realize that the decorator was not properly typed. Obviously a plain `Callable` leads to Any and the expected type is therefore Any (i.e. there are no expected completions).
