### ISSUE TITLE
Virtual environment path cannot contain reference to user home directory.

### ISSUE THREAD

**Issue by odiroot** [davidhalter/jedi#1941]
I'm using Jedi through _python-lsp-server_ under Sublime Text 4 (probably irrelevant).

I want to configure LSP/Jedi to use my _virtualenvwrapper_ based environments.
E.g. I set 
```json
{
    "pylsp.plugins.jedi.environment": "~/.virtualenvs/myenv"
}
```

Unfortunately Jedi cannot deal with it due to the way it resolves the Python path.
https://github.com/davidhalter/jedi/blob/a28bd24befa4331101d151df10445367de8df16a/jedi/api/environment.py#L377-L380

I found that adding just one line would resolve the problem:
```py
def _get_executable_path(path, safe=True):
    """
    Returns None if it's not actually a virtual env.
    """

    if os.name == 'nt':
        python = os.path.join(path, 'Scripts', 'python.exe')
    else:
        python = os.path.join(path, 'bin', 'python')

    python = os.path.expanduser(python)   # Here
    if not os.path.exists(python):
        raise InvalidPythonEnvironment("%s seems to be missing." % python)

    _assert_safe(python, safe)
    return python
```

**Comment by davidhalter** [comment]
I feel like it was intentional to not use `expanduser` everywhere. I feel like this is something that pylsp should probably do. But maybe others want to chime in and give their opinion.

My feeling is that a library should not just do expanduser in random places, that should be done by the software that uses Jedi. But that's just my feeling.

**Comment by odiroot** [comment]
Ok, I can see how you can see it irrelevant at the level of Jedi.
