### ISSUE TITLE
I would like to contribute as translator

### ISSUE THREAD

**Issue by AlmirPaulo** [davidhalter/jedi#1963]
Hi, 
I have used Jedi-Vim in the past and I was thinking of translating the docs it shows about Python. I suppose it's here on Jedi. Does anyone could help me find this pieces of code? 
I would love to contribute to the project.

**Comment by davidhalter** [comment]
Hi Almir. Thanks for reaching out, but I currently don't have plans to translate the documentation, because that would mean we have to somehow maintain it. Currently the docs do not build correctly, so that is something you could definitely help us out with.

But for now this is just not a priority, because we have to maintain translations as well.

**Comment by AlmirPaulo** [comment]
Ok, I see. 
Well, if someday you change your mind I will be happy to help with the translation process. :)
