### ISSUE TITLE
Question: making jedi understand dynamically managed imports

### ISSUE THREAD

**Issue by MichalHe** [davidhalter/jedi#2011]
Hi, I am working on a project that uses a custom module finder and loader to facilitate separation guarantees between project's submodules. To illustrate, we have a following module structure
```
actors/
    |- myactorA/
         |- actor.py
         |- libraries/
             |- libraryA.py
    |- myactorB/
         |- actor.py
         |- libraries/
             |- library.py
``` 
The goal is to make actors unaware of other actors. Actor's code looks in the following fashion:
```
# actors/myactorA/actor.py
from project.actor.libraries import libraryA
```
The framework resolves the import to `libraryA.py`.

Question:
- Is there any way to make jedi understand the (nonstandard) import mechanism?
- If not, could you provide me with some pointers where can I start implement such a feature into (my fork of) jedi. I understand that a custom import resolution might not be widely used, thus, having such a feature might incur more maintenance cost than benefits to the end user.

Thank you very much.

**Comment by davidhalter** [comment]
This is not supported at the moment and there are no plans to. Why is the special import system a requirement? Why don't you work with the other tools that Python gives you?

There might be ways to work around the issue if you use Interpreter mode and set the correct import logic there (Jedi mostly uses importlib).

I'm closing, because there won't be an implementation here, but I'm happy to keep responding here.
