### ISSUE TITLE
Incorrect call signature with wrapt decorators

### ISSUE THREAD

**Issue by mrclary** [davidhalter/jedi#2030]
When using `wrapt` decorators, `jedi` returns incorrect call signature.

MWE:
```python
from functools import wraps
import jedi
from pathlib import Path
import sys
from wrapt import decorator


# wrapt decorator returns wrong call signature
@decorator
def wrapt_decorator(func, instance, args, kwargs):
    result = func(*args, **kwargs)
    return result


@wrapt_decorator
def my_function(a, b):
    """
    My function

    Parameters
    ----------
    a : TYPE
        DESCRIPTION.
    b : TYPE
        DESCRIPTION.

    Returns
    -------
    result : TYPE
        DESCRIPTION.

    """
    return None


# wraps decorator works as expected
def wraps_decorator(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        func(*args, **kwargs)
    return wrapper


@wraps_decorator
def my_function2(a, b):
    """
    My function

    Parameters
    ----------
    a : TYPE
        DESCRIPTION.
    b : TYPE
        DESCRIPTION.

    Returns
    -------
    result : TYPE
        DESCRIPTION.

    """
    return None


if __name__ == '__main__':
    my_function   # line 69, column 10
    my_function2  # line 70, column 10

    source = Path(__file__).read_text()
    env = jedi.create_environment(sys.executable)
    script = jedi.Script(code=source, environment=env)
    print(script.help(line=69, column=10)[0].docstring())  # Bad call signature
    print(script.help(line=70, column=10)[0].docstring())  # Correct call signature

# Result:

# decorator(wrapper=None)
# AdapterWrapper(*args, **kwargs)
#
# My function
#
# Parameters
# ----------
# a : TYPE
#     DESCRIPTION.
# b : TYPE
#     DESCRIPTION.
#
# Returns
# -------
# result : TYPE
#     DESCRIPTION.

# Expected:

# my_function(a, b)
#
# My function
#
# Parameters
# ----------
# a : TYPE
#     DESCRIPTION.
# b : TYPE
#     DESCRIPTION.
#
# Returns
# -------
# result : TYPE
#     DESCRIPTION.
```

I'm using Python 3.10.13 and Jedi 0.19.1

**Comment by davidhalter** [comment]
When I read the wrapt code, all I see is very complicated decorators. You should probably check with them how to make this work. If it doesn't, I would need a way more precise description what Jedi would need to change, so we could actually talk whether that makes sense.

I'm closing, because I doubt that this is something Jedi will ever support.

@mrclary Please try to be more specific with your issues. This is a "library does not work with Jedi" issue, which is not what we're about here. We are about "this use case of 5 lines of Python does generate wrong signatures, is it worth supporting it". So reducing to the essential problem is very very helpful.

**Comment by mrclary** [comment]
@davidhalter, thanks for looking at it. I agree that the issue description should be more specific. I tried to investigate myself but was unsuccessful. I was hoping that someone with more intimate knowledge could provide some insight, which you have done. I'll pursue this with `wrapt` when I get more time, but for now I'll just use `functools`.

**Comment by davidhalter** [comment]
It's better to stick to the stdlib anyway IMO.
