### ISSUE TITLE
Request: Add `name` optional argument to Script.goto_definitions/assignments

### ISSUE THREAD

**Issue by tkf** [davidhalter/jedi#225]
It could be handy if you can goto definitions or assignments of a name even if the cursor is not over it.  For example, you can use it to implement a command asking the name of the variable to goto.

Original request: tkf/emacs-jedi#56

**Comment by martincmartin** [comment]
Any progress on this?

My current use case: I can't remember the exact name of something or expression / idiom to do something, but I know I use it in a given function, so I want to look up the definition of that function.

Also, when reading the code, without moving the cursor over every symbol as I read it, I see a function call that's 10 lines down and 17 characters over.  Instead of moving there and then finding definition at point, it's easier to just type in the name of the function.  Especially with tab completion!  :)

I use this a fair bit with RTags when working in C++.

**Comment by davidhalter** [comment]
Don't you want fuzzy name search for this? With this I mean not providing a correct identifier but something that sounds like that name e.g. a substring. Some IDE's have that support already.

**Comment by valentjedi** [comment]
That would be just great. Pycharm has this with double SHIFT for example.

**Comment by davidhalter** [comment]
I added this feature in the refactor branch. There's now 4 different methods:

- Script.search
- Script.complete_search
- Project.search
- Project.complete_search

It's pretty much finished. The only thing left to do is documentation.
