### ISSUE TITLE
RFC: Get list of possible exceptions

### ISSUE THREAD

**Issue by dbrgn** [davidhalter/jedi#442]
It would be great if there were a way to get a list of possible exceptions for a function call.

Use case: I'm using an HTTP library. When I use the `lib.get_request('https://some-url')` call, I know that there could be different exceptions like `InvalidURLError` or `RequestTimeout`. I'd like to display the list of these exceptions in my $EDITOR. When choosing one of the items, the try-except block should automatically be added. In editors like vim this could be implemented using the autocompletion dropdown, in editors like PyCharm or Eclipse the "refactoring suggestion" could be used.

Maybe the builtin exceptions should be excluded from that list to avoid clutter. Or as an advanced version, they could be removed as long as they're not mentioned in a docstring.

Any comments about this?

**Comment by davidhalter** [comment]
Hmm while this would be a neat feature, I just don't see how you would properly implement it. Scanning for custom exceptions would probably the only reasonable choice (and just ignoring all the builtin exceptions). However that would still imply a lot of logic and understanding Python code. It's even more complicated than autocompletion, because you have to follow paths that are not relevant for type information and might raise exceptions. After that you have to check if they are handled somewhere already. It's all pretty hard I think.

However I like the idea so much that I'll just leave it open :)

**Comment by davidhalter** [comment]
I thought about this for a bit again. It's just really hard, because this feature needs to work well otherwise it doesn't help at all. It also should work with builtins. At this point it's just really hard to get it working.

So I finally decided not to do this in Jedi. It's on my list of things to think about when/if I ever do a Rust rewrite of Jedi.

**Comment by dbrgn** [comment]
> It's on my list of things to think about when/if I ever do a Rust rewrite of Jedi.

You just invoked the

![image](https://user-images.githubusercontent.com/105168/71778661-de62fc00-2fb0-11ea-8594-66778a6a4520.png)

:wink:
