### ISSUE TITLE
Support arbitrary import hooks

### ISSUE THREAD

**Issue by lordmauve** [davidhalter/jedi#452]
In our project Python sources are live edited in a code repository that is not exposed as a filesystem.

We use import hooks to allow Python to import modules directly from the code repository, so that code changes can instantly take effect everywhere across the organisation (tens of thousands of desktops and servers). This approach is current incompatible with Jedi.

Many other custom import hooks can be written, for example allowing users to implement support for WebDAV, caching to deal with slow network filesystems or source-tranforming importers such as [pyxl](https://github.com/dropbox/pyxl).

All these systems could be supported if Jedi used import hooks to load all source, eg. manipulating paths as dotted module paths rather than filesystem paths, and calling the ``loader.get_source(fullname)`` method of a PEP302-compatible importer to actually load source code.

**Comment by fitermay** [comment]
Sorry for not replying earlier. Forgot to verify my github email so I didn't get a notification of your reply. 
In my particular case some packages are local and some are stored in the remote repository/db. The path separator for the remote packages is '/' while for local packages (loaded with standard importers) is \ since the code is running on windows. This can be worked around by converting all paths to fake windows paths when giving them to jedi and then converting back when retrieving the files. However, even with this workaround replacing _Importer would not quite suffice.

At the very least it would also require replacing the call to open(...) in 'check_fs' in imports.py and 'getmtime' in cache.py.  

Also, calls to os.path.exists and os.path.isdir may need to be replaced if used outside of _Importer. In my particular use case I don't think I need to replace them  because the remote repository contains only pure python modules and outside of imports.py these calls are only used to do stuff with compiled modules or for support of some specific frameworks. In the general case I think they would need to be replaced. 

Please let me know your thoughts. Thanks!

**Comment by davidhalter** [comment]
Hmm. I think that we shouldn't just replace all the calls in a simple way. There should be an abstraction that handles something like this. But such an abstraction is not that easy to design.

I think a solution should also be good enough to work with Jython and other tools that modify the import logic. But this is a side note, because I think that if we do it properly, everything will work out, because your requirements are quite big.

**Comment by davidhalter** [comment]
While this would certainly be neat it's not anywhere on my to do list and I'm just closing it, because I think it would be quite hard to do it. If a company wants to pay for this, be my guest. But otherwise this is not going to happen, since open source projects are definitely not using such obscure things.
