### ISSUE TITLE
About Funcation

### ISSUE THREAD

**Issue by zhangziang** [davidhalter/jedi#459]
Can i get a funcation with a pair of parentheses when I select a funcation?
thx!

**Comment by davidhalter** [comment]
@zhangziang If you're using jedi-vim, you won't have this option, because it screws up the autocompletion for brackets.

If you're not using jedi-vim, I would argue like @asmeurer that this is the job of IDE's. You can easily check Jedi's results for its type (`completionobject.type == 'function'`) and then act accordingly.
