### ISSUE TITLE
Feature Request: System File Path Completion

### ISSUE THREAD

**Issue by blink1073** [davidhalter/jedi#493]
I've tried this before and it works:  http://stackoverflow.com/a/5638688. 
It would be nice if Jedi had this built in.

**Comment by davidhalter** [comment]
Took me a while, but this is finally ready. I'm still working on a few cases like completions in `os.path.join`, but it's looking pretty good already. Will be part of the next release.

**Comment by blink1073** [comment]
Sweet, thanks again!

**Comment by davidhalter** [comment]
Now I actually added a few cases that complete inside os.path.join. It's pretty cool, I like it a lot. Should probably add fuzzy completions.

**Comment by blink1073** [comment]
That would be amazing!

**Comment by davidhalter** [comment]
@Carreau, @takluyver  Can you try this out with IPython and see if it works for you guys? It is not released, yet. It's just on master. I feel like it works pretty well IMO. It's definitely more precise than the builtin IPython file completions. However in some cases now, file completions in IPython are duplicated, like in the case of  `os.path.join('/usr/lib`. Jedi completes to `lib'` and IPython to `/usr/lib/`.

The completions are a bit different, because Jedi looks at the context and checks for os.path.join. So you could complete something like `os.path.join('/usr', 'lib` as well. 

Is it a reasonable to eventually just remove IPython file completions or do you guys want to keep that?

**Comment by davidhalter** [comment]
@micbou Do you have a bit of time? I have no Windows and the appveyor tests are failing. I'm not really sure why. See https://ci.appveyor.com/project/davidhalter/jedi/build/job/6lm4ccp6ueuolm8n.

The context of the failing test is file path completions and I'm not sure why it doesn't work. Essentially the code is in `jedi/api/file_name.py` and all other tests about this feature are passing on Windows/Linux.

**Comment by davidhalter** [comment]
@micbou Sorry for the ping, was able to resolve it.
