### ISSUE TITLE
goto_definitions and contextmanagers

### ISSUE THREAD

**Issue by davidszotten** [davidhalter/jedi#494]
when i invoke goto_definition on a function decorated with `contextlib.contextmanager` i end up in contextlib. is this a known limitation or a bug?

thanks!

**Comment by davidhalter** [comment]
It's something I have tried to explain repeatedly, but it doesn't seem to make sense to users, so I will probably just change the behaviour. Have a look at https://github.com/davidhalter/jedi-vim/issues/348 e.g.

**Comment by davidszotten** [comment]
apologies. i did eventually come across that and switched to mostly using goto-assignment. having it jump to import statements first is less useful to me (so far i always find myself calling it again immediately), but there may well be use cases i've not come across yet

**Comment by davidhalter** [comment]
Well it's ok if you close it I guess, because there's still other issues around that cover this (at least that one). I don't think you are wrong. At all. I'm just saying I've had other intentions behind `goto_definitions` originally, but it seems to only confuse people, so I guess we will be changing it, which means we will add another API call (`goto_assignments(follow_statements=True)` or something like that.
