### ISSUE TITLE
fast_parent_copy extremely slow (>1 minute)

### ISSUE THREAD

**Issue by wilywampa** [davidhalter/jedi#497]
In jedi-vim, `fast_parent_copy` is called every time the cursor moves in insert mode, so it needs to be quick. I was getting an extreme amount of lag in some cases and tracked it down to this function. I measured its execution time and compared it to `deepcopy` and `fast_parent_copy` is usually faster, but when inserting text near the top of the linked file, `fast_parent_copy` is hundreds of times slower:

```
fast_parent_copy took 101.130624 sec ; deepcopy took 0.252974 sec
```

Here is the (somewhat contrived to demonstrate the problem) code that resulted in that timing: https://gist.github.com/wilywampa/37cbe9051edde8f74e32

Each paragraph with a new figure seems to exponentially increase the time `fast_parent_copy` takes to complete.

**Comment by davidhalter** [comment]
Hmm, I tried to reproduce it, but couldn't. It doesn't work that way anymore. `call_signatures` is not using `fast_parent_copy` any more, which is now called `deep_ast_copy`.

I also think that this speed issue would not core any more, because `deep_ast_copy` is way simpler now. It just tries to copy `children` and behaves differently for parser nodes and leaves. Before it was a complicated version of `deep_copy`, that could have worked for a variety of structures.
