### ISSUE TITLE
Writing a function with colon

### ISSUE THREAD

**Issue by jonathan-s** [davidhalter/jedi#553]
When writing a function with colon you get the auto-complete feature with a list of keywords starting with abs. Is there a way of turning this off, because it's quite annoying.

**Comment by davidhalter** [comment]
I have no idea what you are talking about. Please be a bit more precise. Generally reproducible Jedi issues can be described by writing a small Python program, that fails (basically a test).

This is also not the jedi-vim tracker, it's about jedi the library.
If you want to turn certain features off in jedi-vim (or any other jedi plugin), please read the corresponding documentation.

**Comment by davidhalter** [comment]
ping

**Comment by sadovnychyi** [comment]
I got this problem as well in sadovnychyi/autocomplete-python#17

Its easy to reproduce it in the terminal with JEDI completions used, just type `def bla():` and press tab:
![image](https://cloud.githubusercontent.com/assets/193864/8348150/2b932c30-1b42-11e5-90ea-a39c4a94e8c1.png)
You will get a lot of completions and its a bit annoying when you are getting them automatically. In my plugin I resolved it my ignoring API calls on requests with `:` suffix.

What we are doing wrong and what's the right way to fix it?

**Comment by davidhalter** [comment]
Why is it wrong to get a lot of completions there?

**Comment by sadovnychyi** [comment]
For example, in Atom, you can select from autocompletions by both tab and enter.
so when you type `def bla():` and hitting enter, you are getting `def bla():abs` autocompleted instead of new line. Basically this is key binding problem, but I've removed any autocompletions after `:` in my plugin to avoid this.

I'm sure you can close this issue if this seems normal to you.

**Comment by davidhalter** [comment]
It's totally valid Python code to be able to complete after a colon. You could argue the same for a lot of other occurrences. This is something that you have to solve in your editor. You could just check for `:$` for example (which doesn't solve the issue for a lot of other places).

**Comment by gizemt** [comment]
> when you type `def bla():` and hitting enter, you are getting `def bla():abs` autocompleted instead of new line

YES! I am using Sublime (ST4) and the autocomplete with ':' and '=' annoys me quite much! I don't personally see a case where these would be useful, but maybe they are for some. In any event, how can I disable autocomplete just for these two characters?

**Comment by davidhalter** [comment]
This is probably something that should be handled on the level of sublime text (or whatever plugin it's using). I don't see why hitting enter would need to trigger autocompletion. 

There is currently no functionality to change the behavior and I feel like this should just be handled by plugins.

**Comment by gizemt** [comment]
I believe hitting ":" or "=" triggers the autocomplete, and hitting enter right after that accepts the autocomplete suggestion instead of moving on to a new line. I personally don't see why one would need autocomplete after ":" or "=" in Python but I am not a power user. 
Maybe [SublimeJedi](https://packagecontrol.io/packages/Jedi%20-%20Python%20autocompletion) is a better venue than here to raise this issue. Thanks, David!
