### ISSUE TITLE
low priority feature request

### ISSUE THREAD

**Issue by nigredo13** [davidhalter/jedi#561]
Hi,
I'd suggest a little improvement to defined_names, some type of mark, obviously in a comment.
something like 
### mark ...description...
In big IDEs like xcode or visual studio it allows for visually separate sections of code by functionality.
Ideally it might be a predefined one, allowing to set it via a parameter of defined_names

**Comment by nigredo13** [comment]
I missed the markdown issue... there are 3 diesis before the mark...

**Comment by davidhalter** [comment]
I don't get what you want :)

PS: You can put everything you want to write as "code" after 4 spaces.

**Comment by nigredo13** [comment]
Hi,
my idea is to add a new token to the parser, something like '###_mark ', 
    ###_mark foo management functions
and a new type to the Definition class, for example 'mark'.
So, when you list the various classes and functions of a source file in a side panel, using the 'names' function to implement a code browser, you have a visual separation between sections of code by functionality. Apple xcode uses #pragma mark ...foo

**Comment by davidhalter** [comment]
Can you give me an example, how that would be visually separated?

**Comment by nigredo13** [comment]
Hi David,
what will divide is a instance of Definition class with type 'mark' and 'name' containing the text after the mark.
http://picpaste.com/Screen_Shot_2015-04-07_at_2.02.39_PM-l8Jc7HFy.png
In this link you will see the class browser of xcode, in the list the bold text entries are marks, set with #pragma mark ..text...

**Comment by davidhalter** [comment]
Ok. Thanks!

I think I get it now. But that won't happen. There's just no reason to do it, because Jedi isn't about "comment" analysis or other stuff that is very IDE specific. Jedi is about understanding Python and helping IDE's to understand Python.

This is not something "Python" specific. You can simply scan all lines for `#pragma` and then sort that with your `names` and you have your desired result. It's very easy that way. An API for such simple tasks would just make everything more complicated.

BTW: `defined_names` will be deprecated, there's a more powerful API called `names` now in the current branches.
