### ISSUE TITLE
jedi-vim: "Builtin modules cannot be displayed" error with assignment and goto_definitions()

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#570]
When trying to use `script.goto_definitions()` on the second line, I am seeing this error: "Builtin modules cannot be displayed (None)."

    test = 1
    test

Using `script.goto_assignments` works.

The help of vim-jedi says:

> The difference between `jedi#goto_assignments()` and `jedi#goto_definitions()`
is that the latter performs recursive lookups.

So I assume this should work?

I've started working on a `goto` command for vim-jedi, which would first try `goto_definitions()` and then fall back to `goto_assignments()` - until I've seen the quote from the help.

(I am using v0.9.0)

**Comment by blueyed** [comment]
Turns out that this is a error from the Vim plugin, and that the help is not correct then probably?!

Should it fallback to going to the assignment (according to the help), or should there be a new function `jedi#goto()` that would do this?

**Comment by blueyed** [comment]
Turns out this is a problem with jedi-vim only.

I've sketched some proof-of-concept for a new "auto" mode, where it will fallback to going to the assignment when the definition would be a builtin: https://github.com/blueyed/jedi-vim/commit/8e57de14a1741d789a83ae1ad9bbe9469f549b50

What do you think?

**Comment by davidhalter** [comment]
Hmm why would you want such a command?

I'm not sure if it's a good idea to do that, because basically you're asking for functionality that could be used in other plugins as well. So what I'm saying is, if you're interested in that, do it for Jedi and not jedi-vim. We would need a specification of that command first, though.

BTW: I've thought about adding a parameter to `jedi.Script.goto_assignments` to do something similar to what you're trying to achieve.

**Comment by blueyed** [comment]
Agreed. It should be in jedi-vim.

The main intention here was that I usually use "goto definition", but with builtin types that fails. In that case I'd like to fallback to the assignment.

A related request is in https://github.com/davidhalter/jedi-vim/issues/348 - where you typically want to go to the assignment for decorators.

What would be the parameter for `jedi.Script.goto_assignments`?
How would it help with falling back in `jedi.Script.goto_definitions`?

**Comment by davidhalter** [comment]
Sorry, I thought you were trying to implement it in jedi-vim (because I thought you added a jedi-vim issue).

I realized that most people don't want `goto_definitions` to work as it does. They are rather irritated by it. However, I think `goto_definitions` is an important function, because it gives you access to the type inference. But it's probably not the goto function IDE's want. My idea is therefore to add a param to `goto_assignments` and use it as a second goto command within jedi-vim (instead of `goto_definitions`).

What you want is basically a `goto_assignments` function in its current state and a `goto_assignments` function that does it over and over again until it's not possible anymore. The latter would follow imports, obviously. And maybe also statements (if it's not a tuple or a builtin object).

The command could therefore look like:

    goto_assignments(follow_imports=False)

Do you understand? Do you agree?

**Comment by blueyed** [comment]
Makes perfect sense to me!

However, the "over and over again" part of it seems like it could be optimized to just do what `goto_definitions` does and fall back in case this is not what you'd want.

**Comment by davidhalter** [comment]
It would be less precise (and wouldn't solve the issue with decorators). Also the repeats should be performing quite well. I don't think there's a big overhead when comparing it to `goto_definitions`.

**Comment by blueyed** [comment]
Great.
As for Jedi-vim, would we then have three different commands, with the new one being the default? (Re https://github.com/blueyed/jedi-vim/commit/8e57de14a1741d789a83ae1ad9bbe9469f549b50)
Do you think it makes sense to add "auto" like in this commit, until Jedi provides the new mode?

**Comment by davidhalter** [comment]
For jedi-vim, I would just replace `goto_definition` completely. It's not like anybody really needs that. :)

**Comment by blueyed** [comment]
I don't like the inconsistency, and the old function (wrapper) could be still provided - but would not be mapped by default.
Instead, the new function could be mapped to what `goto_definition` does now.

If we're using a "auto goto" mode, this could be improved later.

I've moved the commit into a PR for now, and changed the defaults/doc: https://github.com/davidhalter/jedi-vim/pull/407

**Comment by davidhalter** [comment]
Yeah, you're right, we could just disable it.

**Comment by blueyed** [comment]
I think this can be closed, as #407 is merged.

There are still issues in this regard however, but more likely related to Jedi: https://github.com/davidhalter/jedi/issues/604
