### ISSUE TITLE
"auto-goto" does not resolve pony-orm's decorators (e.g. with generate_mapping)

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi#604]
TEST CASE:

```
from pony.orm import Database

db = Database('sqlite', ':memory:')
db.generate_mapping()
```

Calling `jedi#goto` on `generate_mapping` will go to `pony_wrapper` in pony.utils:

```
def _improved_decorator(caller, func):
    if isfunction(func):
        return _decorator(caller, func)
    def pony_wrapper(*args, **kwargs):
        return caller(func, *args, **kwargs)
    return pony_wrapper
```

`jedi#goto_assignments()` works.

The issue here appears to be that the auto-goto only skips builtin modules
(before falling back to `goto_assignments`) and it seems like Pony ORM uses
some uncommon wrapping for its decorators (via 3rd party
http://pypi.python.org/pypi/decorator) and that causes Jedi to not resolve it
fully to the internal?!

I assume this needs to be addressed in Jedi, but maybe jedi-vim could do
something here, too?  (by falling back to `goto_assignments`)

**Comment by davidhalter** [comment]
Since you're talking about `jedi#goto`, notice that it's not properly implemented, yet (see the related discussions like https://github.com/davidhalter/jedi-vim/pull/407 and https://github.com/davidhalter/jedi-vim/pull/570, however I couldn't really find the place where I told you that the implementation of mixing `goto_definitions` and `goto_assignments` has some drawbacks).

This one might not even be a Jedi issue, because of that. Maybe we just have to add `goto_assignments(follow_imports=False)` (which I was describing in https://github.com/davidhalter/jedi-vim/pull/570).

**Comment by PeterJCLaw** [comment]
@davidhalter I'm guessing in your last comment you meant #570 rather than https://github.com/davidhalter/jedi-vim/issues/570

**Comment by PeterJCLaw** [comment]
This issue seems like it's potentially relater to #945

**Comment by davidhalter** [comment]
Can you guys recheck with master? #945 has been fixed so this one might have been fixed as well.

**Comment by davidhalter** [comment]
Closing this, because of no feedback.
