### ISSUE TITLE
How can I get all locations of a element with jedi ?

### ISSUE THREAD

**Issue by sametmax** [davidhalter/jedi#611]
I wish to use jedi manually to find all the elements named in a certain way. E.G : if I have the word "index", I want to find all variables, classes, functions, methods and attributes in all importable packages containing the string "index" in their name, and get their dotted path + the module file path containing it (if it exists).

Now the documentation only show high level usages of Jedi : given a script, you type something, it autocompletes it. But since you had to implement a scanner for all modules, and a parser for all elements, I figured Jedi probably can do what I want.

How would I do it ?

**Comment by davidhalter** [comment]
Well it's intentionally documented in the API documentation, because it's not part of the API and it's therefore subject to change.

However if you just try to play with Jedi for a bit, you can try to play with `Module.used_names`, which will give you all the names that are used. After that you can play with the names `Name.is_definition` and `Name.get_definition` and so on.

I will not give you a solution for your problem. I don't have the time to. But if you have further questions I can maybe help you a bit.

**Comment by davidhalter** [comment]
This would be a feature of the parser (that will be released in a few months, hopefully): #630
