### ISSUE TITLE
Fail to complete urllib2 response object

### ISSUE THREAD

**Issue by 19000** [davidhalter/jedi#622]
I am using emacs jedi plugin, and find sometimes it fail to complete.

So I write some code to test.

#### Code below success to complete, which output `"add_data"` method name of `Request` object.
```python
import jedi
source = '''
import urllib2
req = urllib2.Request('https://github.com')
res = urllib2.urlopen('https://github.com')
req.
'''
script = jedi.Script(source, 5, len('req.'), 'example.py')
completions = script.completions()
print completions
print completions[0].complete
print completions[0].name
```

#### But when it comes to the response object, jedi fail to complete, which return an empty list (Only changes `req.` to `res.`, and other lines remain the same)
```python
import jedi
source = '''
import urllib2
req = urllib2.Request('https://github.com')
res = urllib2.urlopen('https://github.com')
res.
'''
script = jedi.Script(source, 5, len('res.'), 'example.py')
completions = script.completions()
print completions
print completions[0].complete
print completions[0].name
```
----------------
There are other cases like `cursor` object in `MySQLdb` fails to complete too.
I am new to jedi. Is this a bug or feature?

**Comment by davidhalter** [comment]
Well in general Jedi can fail. Some Python things are just too hard to understand!

In this particular case, `Request` is a class and therefore pretty easy to understand. `urlopen` is a function that is not very complicated, but the sub calls are. I'm guessing that it cannot understand dictionary modifications, within `urllib2`. (Probably doesn't understand `self.handle_open`).

I'm closing, because it's documented that Jedi doesn't understand certain things, you can read it up.
