### ISSUE TITLE
Support for __slots__

### ISSUE THREAD

**Issue by d42** [davidhalter/jedi#652]
In my humble opinion, if a class defines its slots it wouldn't hurt to provide them for completion without having to explicitly provide values for them in the code.

If any of the great and benevolent developers of this fine project shares my view on this case, I'd like to inquiry whether this feature hasn't been included because of technical reasons, or simply because of fairly low demand? :3

kkthx.

**Comment by davidhalter** [comment]
> because of technical reasons, or simply because of fairly low demand? :3

Because of fairly low demand. It's not like a lot of people are using __slots__.

**Comment by davidhalter** [comment]
What I just realized for this issue as the central thing: We should add a `evaluate.representation.Class.py__slots__()` function that returns the `__slots__` for a class.

    def py__slots__(self):
        for typ in iterable.py__iter__(evaluator, evaluator.find_types(cls, '__slots__')):
            if isinstance(typ, CompiledObject) and isinstance(typ.obj, str):
                # If it's a CompiledObject and a string, we can continue adding those, 
                # if it's something else just ignore it. It's probably a very complex construct,
                # that Jedi cannot infer.
                yield typ.obj

Maybe we should then also add a `def mro_slots()` to be able to access all the slots from all the classes.

**Comment by remorses** [comment]
This issue is very old but I think it would be awesome to add __slots__, would be a pull request appreciated?

**Comment by davidhalter** [comment]
Yeah, feel free to create a PR :)

**Comment by davidhalter** [comment]
@remorses Still interested in creating a pull request? I'm happy to assist :)

**Comment by davidhalter** [comment]
I'm closing for now. It hasn't received enough upvotes. If somebody wants to do the work, I'm happy to merge, if the work is good. It shouldn't be too much work. 

I haven't seen a ton of `__slots__` usage, where this would be practical. If other people still want to see this happen, please comment! :-)

**Comment by asmeurer** [comment]
It's probably because `__slots__` is redundant. If a class defines `__slots__`, those attributes still have to be manually assigned somewhere, which jedi would likely pick up on. So the only reason you'd need this feature is if somehow a class has `__slots__` but assigns them in a way that jedi cannot detect. 

Also note that just because a name is in `__slots__` doesn't mean it has to be assigned. The restriction is the opposite: that names that aren't in `__slots__` cannot be assigned. It also doesn't apply to class variables or `__getattr__`. So I don't really see how it can be that useful to jedi, but maybe there are some use-cases that I'm not seeing. 

I am surprised that jedi apparently doesn't follow `__dir__`. I would expect

```py
def __dir__(self):
    return self.__slots__
```

to produce the desired behavior, but in my test, it doesn't.

**Comment by davidhalter** [comment]
It follows `__dir__` when using `Interpreter`. In all other cases, dir is probably hard to infer, because if people use it, it's something highly dynamic.

The only value people could infer from autocompletion is if you write 

```
class X:
    __slots__ = ('foo', 'bar')

    def __init__(self):
        self.f  # <--- complete here
```
You would have proper completions for `foo`. But it's just not worth the work IMO.

**Comment by asmeurer** [comment]
I actually am using Interpreter. But I think there are some other problems with my use of Jedi and I haven't had time to dig into them.

**Comment by davidhalter** [comment]
It works for me in IPython.
