### ISSUE TITLE
goto_definitions ignoring absolute_import directive

### ISSUE THREAD

**Issue by mxmul** [davidhalter/jedi#655]
I'm working on a (py27) project where a submodule has the same name as the top-level package, and `goto_definitions` isn't working as expected. I've been able to reproduce with a simple project that looks like this:

```
example/
├── __init__.py
├── submodule
│   ├── __init__.py
│   └── example.py
└── util.py
```

where `example.py` has contents:
```python
# -*- coding: utf-8 -*-
# example/submodule/example.py
from __future__ import absolute_import

from example.util import some_function
```

With this setup, jedi finds no definitions for `some_function` on line 5 of `example.py`, but it works fine if I rename the file:
```python
>>> import jedi
>>> script = jedi.Script(line=5, column=25, path='example/submodule/example.py')
>>> print script.goto_definitions()
[]
>>> script = jedi.Script(line=5, column=25, path='example/submodule/copy_of_example.py')
>>> print script.goto_definitions()
[<Definition def some_function>]
```

**Comment by davidhalter** [comment]
This is something that doesn't just easily work, because Jedi doesn't know the entry point of a script (there's no API for that anyway, yet). Therefore Jedi tries to guess: It tries to find the file that might be responsible: `example.py`.

So we might be able to fix this somehow, maybe we should just try to continue with parent directories, if type inference fails on completion.

**Comment by davidhalter** [comment]
As long as Jedi doesn't support projects, this is definitely not an option. Once Jedi supports projects (i.e. setting a default path), this might work way better.
