### ISSUE TITLE
unable to complete on "slightly complex" object

### ISSUE THREAD

**Issue by kraxli** [davidhalter/jedi#672]
Hi,
I posted this originally on the jedi-vim issue list (https://github.com/davidhalter/jedi-vim/issues/438) but I was told that this is jedi issue so I moved it here.

Jedi is not completing slightly complex objects as "x" in the following example:

```python
import pandas as pd
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']), 'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
x = df.head(2)
x.        # no completion on this data-frame
```
E.g. in Vim, the command line shows: "=jedi#complete_opened(0) Omni completion (^O^N^P) Pattern not found"

Another example with numpy: 
```python
ll = [i for i in range(0,int(30e3))]
nn = np.array(ll)   
nn.   # no completion
```
Could anybody please help out on this or does anybody have suggestions what could go wrong? It would be great if this issue could be fixed as it would make editors as vim really nice and competitive to program python in.

Many thanks, David

**Comment by davidhalter** [comment]
Pandas support is not very good as well as numpy. I don't want to go into the details, because I've mentioned it quite a few times before in other threads (about numpy and pandas, just search it in both the jedi and jedi-vim tracker).

There's reasons for this, they are definitely fixable, but it's not my focus and unless you don't try to invest time by fixing it, there's probably not just a solution. If you invest the time, I will also gladly point you at the issues.

I'm closing for now, because this is a duplicate https://github.com/davidhalter/jedi/search?q=pandas

**Comment by kraxli** [comment]
Ok I see - thanks. I do not know how Jedi really works. However, somehow it probably refers the type from an object. Having the type, couldn't one simply execute the ```dir()``` function on the type? So for example 
```python
dir(np.ndarray)
# or
dir(np.array)
```
?

**Comment by davidhalter** [comment]
`array` is not a type IIRC. It's a very complex function that Jedi doesn't understand correctly. This is most of the time the issue with numpy/pandas, they use very sophisticated stuff (like setattr and so on) that makes completion very hard. Also sometimes it has to do with builtins that Jedi doesn't understand.
