### ISSUE TITLE
How to differentiate a class attribute from a simple local assignment

### ISSUE THREAD

**Issue by MathieuDuponchelle** [davidhalter/jedi#695]
I'm trying to list all the attributes of a class, but I have trouble figuring out how to do so, to be honest I find the whole API a bit confusing, for example get_names returning `Definition`s even though a class named Name exists ? scratching my head here :)

Anyway, given a such a module:

```
class Foo:
    def __init__(self):
        self.my_attribute = 57
        not_an_attribute = 48
```

What would be the most correct way to achieve my goal and end up with ['my_attribute'] somehow?

I see half a dozen potential entry points for this task, but after some fiddling around I can't find anything that would suit my needs, please tell me I'm dumb :)

**Comment by MathieuDuponchelle** [comment]
Note that I do not care about attributes defined outside __init__ or attributes dynamically generated (for now)

**Comment by MathieuDuponchelle** [comment]
FWIW, here is my (admittedly very naive) attempt : https://github.com/hotdoc/hotdoc_python_extension/blob/develop/hotdoc_python_extension/python_extension.py#L150 . It does seem to work reliably on a medium-sized project, I'm sure there are flaws with it, but at least it covers the most important parts:

* attribute defined at init
* outside init
* and multiple definitions on the same line (`self.foo = self.bar = 42`)

I'd still be very interested in a less hacky approach.

**Comment by davidhalter** [comment]
Mathieu, I'm really sorry for the delay. I have written an answer before (though still to late), but it got deleted. So here it comes again:

For your initial problem there's not really an API currently. You are now trying to create a prototype based on `self._definition` that is not public. This might work, but be careful, we might break it.

> get_names returning Definitions even though a class named Name exists ?

I don't see where a Name would exist. Clearly names exist within Jedi, but that's something entirely different, because you will never see them in the public API.

> here is my (admittedly very naive) attempt

You're on the right track, but I think it could be way nicer. You can just get the current class `cls = self._definition.get_parent_until(tree.Class)`, wrap it `cls = evaluator.wrap(cls)`, instantiate it: `instance = evaluator.execute(cls)` and use `instance._self_names_dict()` on it. This is way better than actually creating all of that stuff yourself. I'm a bit confused by that function as well, because it has an `add_mro` argument that isn't used, we might correct that as well (because you might need it).

Once you have a working prototype I would be interested to merge upstream. Note: Use the linter branch please (also for your local development).

**Comment by MathieuDuponchelle** [comment]
Thanks for getting back to me on this :)

My use case is still very alpha, and I simply wanted to port the current version of the extension to jedi to get it to work regardless of the version of python being documented, it now seems to be the case, the only user for this extension is the "core" of my documentation tool, where I use it instead of sphinx mostly because it felt cool to have the tool bootstrap its own documentation, so working more on this is not yet on my schedule.

Please ping me if you expose some higher-level API before I find the time to tackle this :)

Thanks for your work on jedi, cheers!

**Comment by davidhalter** [comment]
Thanks! I will close then :) Let me know if you work on this again.
