### ISSUE TITLE
Strange completion for argparse --- is it possible to disable it?

### ISSUE THREAD

**Issue by Rmano** [davidhalter/jedi#723]
Heads up: probably this is an operator error, but I am quite unable to find a solution myself. 
I use quite a lot `argparse`; consider the snippet: 

```
import argparse

# description 
parser = argparse.ArgumentParser(description="Convert data file in xlsx")
# one  positional (mandatory) argument
parser.add_argument('fname', metavar='fname',
                   help='input file (mandatory)')
# go
args=parser.parse_args()
```

Now, if I write for example `args.` the autocompletion suggestion is strange --- it adds and underscore and it's more harmful than useful: 

![selection_077](https://cloud.githubusercontent.com/assets/6414907/15267820/e4110a0a-19cc-11e6-9d78-fd4445ca4da8.png)

Is it possible to selectively disable completion for it?

**Comment by davidhalter** [comment]
Well to put it short:
The added underscore is a VIM issue and cannot be solved by jedi-vim. You can however change your `completeopt` settings (IIRC). 

Disabling will also not be possible. The argparse output is quite obviously wrong, but that's probably hard to change, because some things are just too hard for Jedi to understand.

Let me know if you have any other issues.
