### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by dionyziz** [davidhalter/jedi#760]
I did not find a security reference in the [documentation](http://jedi.jedidjah.ch/en/latest/#resources) or in existing issues. My question is the following:

Given that I use jedi to autocomplete code in a malicious python file I have opened, is it possible for the author of that file to gain command execution on my machine? What is the threat model of jedi and its specific security assumptions?

Thank you.

**Comment by davidhalter** [comment]
It's pretty easy:

There's no Python code execution except in one place: sys path manipulations. An attacker could gain command execution on your machine, but only if he actually tries. This is something where the attacker has to intentionally point an attack towards Jedi users. It's definitely something that is on my list to fix. This is definitely doable and not a huge fix.

The bigger issue (longterm and unfixable) is that it's always possible to get command execution by getting compiled plugins (written in C). There you could pretty much do anything and Jedi would just load them anyways, because there's not really much else Jedi could do.
However, I've been arguing that this is not that bad, because this module would get executed *anyway* once you run python. Where as the `sys.path` hack might not.

But even there: If you download code you want to eventually run it. It's funny how most people (including me) just do that anyways, hehe. That's where the big risk of command execution lies.

What do you think?

**Comment by dionyziz** [comment]
My threat model involves actors that target me specifically and know my installation, including the fact that I use jedi as part of the YouCompleteMe plugin for vim on my specific version of vim using my specific vimrc and operating system. (To understand my specific threat model, see [my treasure hunt](https://dionyziz.com/hackme/). Malicious actors know about my exact setup because [it is published](https://github.com/dionyziz/config) by choice.)

When I open up a source code file written, for example, in Python with my editor, I do not always intend to run it as it is. I often load up source files to inspect them, and sometimes this inspection is exactly to see if they do something malicious. If they load up unknown Python libraries that I have not installed using pip, I will not run the code. If they are complicated enough that I cannot inspect the whole source code, I will also not run them.

In order to run some Python code, I need some assurance that the code is secure: Either a signature by an author that I trust (because, for example, I have a GPG trust path towards them), or a signature by a packager I trust (because, for example, it has been packaged by a brew or Debian maintainer), or because the code is simple enough and I have inspected it manually. The last case involves opening the file in vim but not necessarily running it.

Could you please describe what the sys.path attack exactly is? Do you have a proof of concept I could experiment with? How do you plan on fixing it? Could you also describe the exact circumstances in which a Python C plugin could be executed by Jedi? Could Jedi possibly be configured to ask before executing a new Python C plugin? Do you think that's a possible fix?

Thank you.

**Comment by dionyziz** [comment]
Can you explain the sys.path manipulation you have in mind?

**Comment by davidhalter** [comment]
I would like to be able to give you a concrete plan on tackling those security issues. But at the moment I just don't have the time to dive into this. Other things are more important. 

Basicallly the `sys.path` manipulation should just be calculated statically. This involves quite a few changes there (I think it's very hard to pass the current test suite). Most important would be to secure access to `os.path.*`. However that's a separate requirement that could as well be done independently.

> Could you also describe the exact circumstances in which a Python C plugin could be executed by Jedi?

`from ext_module import *` is enough.

> Do you have a proof of concept I could experiment with?

I won't, because unless you solve quite a few other things before, I will not accept any PRs regarding this. First type inference in Jedi of `{'a/b': 1, 'c': 'string'}[os.path.join('a', 'b')] should return `int()`, before that there's not really a need to mitigate attacks IMO.

**Comment by dionyziz** [comment]
OK. To understand where this security issue comes from exactly, do you have a concrete example that illustrates how a dedicated attacker could abuse the current jedi implementation through sys.path manipulation? What would be the exact steps needed to achieve arbitrary command execution?

**Comment by davidhalter** [comment]
I don't have one, but it's really easy.

Just read the `sys_path.py` code and you'll easily see why this can happen. I don't think it needs a proof of concept when it's clearly exploitable, hehe.

**Comment by davidhalter** [comment]
Ok. Now the sys_path security issue has been resolved. The only issue now is c-builtin modules. We could probably somehow stop users form accessing non-root modules? Would that be secure enough for you?

**Comment by davidhalter** [comment]
In the project branch there's now a param called: `load_unsafe_extensions=False`. By default it only loads extensions on the sys path, but not in the local directory. So all those modules that were installed (where there was code execution already through executing setup.py).

Now in your case you could download arbitrary code/binaries, work on it with Jedi and there shouldn't be any code execution anymore.

However as soon as you install something you might be in danger, but IMO this is not an issue, because the attacker has code execution privileges at this point anyway :).

This will be released in 0.17.0.
