### ISSUE TITLE
Code introspection unable to locate definitions when working with "Abstract super-classes" (sub class defines method)

### ISSUE THREAD

**Issue by mkrahal** [davidhalter/jedi#809]
I have been working with abstract super-classesc using elpy in conjuncture with jedi (v 0.9.0)  and have noticed that it is unable to locate definitions when working with a super class that expects part of its behaviour (a method) to be determined by a sub class.

I have attached a small piece of code to help reproduce the issue. In a nutshell, all jump to definition attempts are unable to locate the definition of the "func2" method that implements code expected by the super-class' "func1" method. In this example the call to the "func2" method within the "Super" class invokes a new inheritance tree search from bottom-up, which locates "func2" within the "Child" class.

    class Super():
        def func1(self, data):
            self.word = data
            print "Now within Super class - func1 method and self.word contains %s" % (self.word)
            self.func2()

    class Child(Super):
        def func2(self):
            print "Now within Child class - func2 method, self.word contains %s" % (self.word)

    i = Child()
    i.func1("test")

When the user attempts to jump to definition from the "self.func2" method call on line 5 no definition is located. I think the issue here is that jedi does not re-initiate an independent inheritance tree search to locate the definition, but rather expects it to be defined before the call.

**Comment by davidhalter** [comment]
Your analysis is quite good. I haven't actually come across this issue just by using Jedi. But I have tried writing a linter where this was actually a big issue.

I'm still not sure what the best solution is for this one. It's quite tricky since it involves a lot of searching (resursive by all means and multi-file). It's not something that's just solved without thinking a lot about the performance impact.

**Comment by davidhalter** [comment]
I decided not to implement this. This is for a couple of reasons.

1. Features like this have a performance cost and doing a dynamic search, where the class is used is usually quite costly (especially if you have to do it in a lot of places, if an attribute is not defined in the class).
2. I recently changed my opinion on these kind of class structures. I have used them myself for quite a long time, but I now think that it's an anti pattern. The control flow is very unclear and it's very unclear how this code behaves (if you don't have the exact knowledge of the inheritance structure). My way to do stuff like this is either composition (i.e. nesting objects) or having a base method that throws a NotImplementedError. The latter can obviously be improved with `abc`. Generally I try to avoid inheritance anyway, because it lead to a huge complicated mess every time I have used it.
