### ISSUE TITLE
Jedi fails to initialize Python - depreciated method in Sphinx 1.6.3

### ISSUE THREAD

**Issue by ryanjdillon** [davidhalter/jedi#939]
After upgrading to `sphinx 1.6.3`, I began to get the following error from `jedi`:
```
Error detected while processing function jedi#init_python:
line    7:
Error: jedi-vim failed to initialize Python: jedi#setup_py_version: Vim(py3file):/usr/local/
lib/python3.5/dist-packages/sphinx/util/compat.py:40: RemovedInSphinx17Warning: sphinx.util.
compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' inste
ad. (in function jedi#init_python[3]..<SNR>48_init_python[50]..jedi#setup_py_version, line 1
6)
```
After downgrading to `sphinx 1.5.6`, `jedi` initialized just fine again.

**Comment by davidhalter** [comment]
The thing is: That's a warning. You probably are using certain settings that make warnings errors. I think that somewhere sphinx is imported (maybe numpydoc?!). However that's definitely not a Jedi issue, because Jedi is only using the library `numpydoc` (that uses sphinx). However since there's pretty much no magic involved (it's a simple call), I think if anything you have to track this down and talk to the numpydoc guys or sphinx or whoever.
