### ISSUE TITLE
Generate typehints for python3

### ISSUE THREAD

**Issue by robinro** [davidhalter/jedi#987]
jedi knows the types of all `return` values and via usages also the argument types.

It might be possible to use this to automatically generate type annotation (in-place or in stub files).

**Comment by davidhalter** [comment]
It would actually be possible to do this for Python 2 as well (with type hint comments). IMO this should be a separate project at least at first. I think I have done something similar in https://github.com/davidhalter/jedi/issues/662#issuecomment-165857511. The script there might be out-of-date and would probably need to be changed a bit, because it uses internals that might have been removed.

**Comment by balta2ar** [comment]
Take a look at recently open sourced library https://github.com/dropbox/pyannotate

**Comment by MohamedAlFahim** [comment]
@robinro One issue is that Jedi might have to scan multiple files to distinguish objects with similar methods, and this can strongly decrease performance. Nonetheless, it is a useful feature to implement. Jedi could infer the possible type by checking if a candidate type contains the methods used in the file.

**Comment by davidhalter** [comment]
From #801:

> Is possible output [a doctsring] like:

> `set_value(self, value: int) -> (str, None):`
   `blab docs`

**Comment by davidhalter** [comment]
You can now use `Definition.get_type_hint() in combination with `Definition.docstring(raw=True)` to get what you want in #801 as well.

Generally this function is probably quite slow, so be careful in using it.
