### ISSUE TITLE
No call signatures on PyQt5 anymore

### ISSUE THREAD

**Issue by TobiasRzepka** [davidhalter/jedi#989]
With 0.10.2 I could get a call signature for PyQt5 objects, e.g.
`>>> jedi.Script('from PyQt5.QtCore import QTimer\nQTimer.start(',2, 13).call_signatures()
[<CallSignature: start index 0>]
`
0.11.0 returns only an empty list.
Tobias

**Comment by davidhalter** [comment]
What Python are you using?

**Comment by TobiasRzepka** [comment]
I'm using `Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32` with `PyQt5/Qt Version 5.6.0`.
Same behaviour with `Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32` and `PyQt4 Version 4.11.4 (Qt 4.8.7)`
PyQt4/5 were the binary distributions from Riverbank.

**Comment by davidhalter** [comment]
I think I know why this happens. In 3.5 we're using inspect.signature and not a weird way of parsing strings anymore. I think this is a huge gain, because now signatures are actually precise. But for a few non-pythonic libraries this might make problems.

I'm not really sure why this happens, because inspect.signature throws a ValueError if no signature is defined. Maybe there's wrong signatures on QTimer.start?

**Comment by davidhalter** [comment]
What is `inspect.signature(QTimer.start(',2, 13))`?

**Comment by davidhalter** [comment]
Closing, because no feedback. Reopening if this is still an issue.
