### ISSUE TITLE
Not a issue, only a question about Jedi with big files 

### ISSUE THREAD

**Issue by nigredo13** [davidhalter/jedi#994]
Hi,
I've used jedi in my editor for a few years and think it's very good. 
But recently I'm working with other's people sources that contains very big files, more than 100kb.
So, at every character I wrote my poor plugin has to pass 100k of text to the script function, and obviously this turns out very bad.
I really have to pass the entire source or a part of it can suffice to get completions ? If yes how many lines of text ?

Thanks.

Marco

**Comment by davidhalter** [comment]
Hmm I just fixed a few caching issues. It's pretty much ok now for me in a 500k file. It's not "good", but after an initial delay of like 4s it's ok (like 500ms completions). Are those kind of delays what you're complaining about?

**Comment by nigredo13** [comment]
Well, I don't think there is a problem with jedi...
My editor is based on the python binding of gtksourceview, and I suppose that the delay occurs because of the way to get the source is not so immediate. I have not a simple pointer to the text, all times must call a function passing to it two iter, a pointer like used by the text buffer, that too need be computed by the buffer class. So merely the amount of text may be the cause.
If a smaller amount of text could suffice to get the completions the problem is solved.
I tried with a few lines of text around the cursor, but to no avail.

**Comment by davidhalter** [comment]
> Well, I don't think there is a problem with jedi...

I still have no idea how slow the stuff is you're doing. If jedi is not the problem at all, then a question here makes no sense. If jedi's slowing down because of a 100k file that's not good and we can maybe improve. We probably won't improve as much as 10ms per completion, but we can have something like 200ms maybe?

**Comment by nigredo13** [comment]
My original question was: does jedi really need all the file's source to get completions, and principally, at every new character ?
Or may be a part of it, already having the file's path, cached a lot of stuff etc can suffice ?

**Comment by davidhalter** [comment]
Ok. If that is really the issue I would just say - yes (the API itself works with that). If retrieving 100kb of code cannot be handled by an editor, something is very wrong there. Use a different one ;-)

**Comment by nigredo13** [comment]
I know my english is far from perfect, but usually it is understood. 
Perhaps you too are not a native english speaker, or may be something gets in the way all times you read a post and you end thinking everybody is here to criticize you or your creation.
Anyway, right, may be that for editing big files gtksourceview is not the ideal, or may be there are better autocompletions too.

**Comment by davidhalter** [comment]
Well most issues here are actually criticizing jedi. That makes even sense, it's an issue tracker.

If there's an issue like this one, I tend to make assumptions. Never before somebody told me that retrieving the source code is slow. That just doesn't make sense on so many levels (especially for 100k). Giving jedi only parts doesn't work, because without good analysis you wouldn't know where a docstrings starts/ends.
