### ISSUE TITLE
No auto-completion for dynamic attributes

### ISSUE THREAD

**Issue by 0xLeon** [davidhalter/jedi#997]
Jedi version: 0.11.0
Python version: 3.6.3

Using the following test script:
```python
class Foo(object):
	def foo(self):
		print('foo')

class Bar(object):
	def __init__(self):
		self._fooInstance = Foo()

	def __dir__(self):
		return sorted(set(self._fooInstance.__dir__()))

	def __getattr__(self, name):
		if hasattr(self._fooInstance, name):
			return getattr(self._fooInstance, name)

		raise AttributeError('Instance of {:s} has no attribute {:s}'.format(self.__class__.__name__, name))

bar = Bar()
bar.
```
Running the following jedi test:
```python
import jedi

with open('Test.py', 'r') as f:
	src = ''.join(f.readlines())

print(jedi.Script(src).completions())
```

I get the completion for the `Bar` object as if it had it's default `__dir__`. But what I want is the actual output of the `Bar.__dir__`. Because of this, there is no auto-completion for dynamic attributes. In the last line of the test script, I would expect `foo` to be in the auto-completion suggestion, as it's a method of the `Foo` object inside of `Bar`, which handles the `__getattr__` calls to the outer object.

**Comment by davidhalter** [comment]
I can see where you're going with this. I'm not sure if working with `__dir__` is the right idea, I'll just add it to the list of potential features in the future.

**Comment by takluyver** [comment]
FWIW, IPython's completions have used `__dir__` for a long time, and I don't recall having many problems resulting from it. I think this makes sense at least in `Interpreter` for objects that are already initialized; I imagine it's not practical to create instances solely to call their `__dir__` method.

**Comment by davidhalter** [comment]
@takluyver Jedi uses `__dir__` when using the `Interpreter`. The question here is about statically analysing a `__dir__` function and adding the results to the completions.

The big problem is basically just that it's hard to do that not that I don't want to do that ;-)

**Comment by takluyver** [comment]
Ah, gotcha. We're experiencing a problem where we don't seem to get `__dir__` completions using `Interpreter`, and we thought this might be the same issue. I'll investigate further.

**Comment by Cologler** [comment]
@0xLeon Static analysis should not exec any code for avoid the code to do some evil things.

**Comment by blueyed** [comment]
@Cologler 
Could this be whitelisted somethow?
Would jedi.settings work for this?  (since only the user should be able to control it, right)
Should there be a list of class pathes where `__dir__` gets used from?

But since `__dir__` appears to be a list of names only, maybe a custom dunder method could be used, which would return information about the type and signature for functions then.

(I just added a `__dir__` method for Neovim's RemoteApi (https://github.com/neovim/python-client/pull/346/files).  In this case code gets executed on first use.  IIRC there information is available about the args being used/supported, which could be communicated back to Jedi via something like `__completions__`)

**Comment by blueyed** [comment]
@Cologler 
Sure, therefore I think a whitelist would be needed - e.g. I would like to enable `neovim.api.common.RemoteApi` then in my case.
Not sure about `super()` calls then though - maybe Jedi could assume `[]` then, if not whitelisted.

However, I think something like `__completions__` would be more benefical.

Or, we culd have something in `jedi.settings` directly, e.g. a callback that would get information like the classname and other required info, and would return the completions then to Jedi - kind of a Jedi plugin then.

**Comment by davidhalter** [comment]
Since we don't execute anything in Python files, there's no reason to use something like `__completions__` anyway. This will also not change, because if you don't start executing Python code you are going down a very dangerous path.

Compiled files (builtins, etc) are executed at the moment, but this might even change once we understand typeshed.

**Comment by davidhalter** [comment]
Fixed this. Obviously without code execution.

It is a heuristic and I don't think I would do more than this. It's pretty much impossible to catch all cases, because there's just so much dynamic stuff happening. For now it pretty much works for this:

```
def __getattr__(self, name):        
    ...                             
    return getattr(any_object, name)
```

It is important that the return contains getattr directly, otherwise it
won't work anymore. It's really just a stupid heuristic. It will not   
work if you write e.g. `return (getatr(o, name))`, because of the      
additional parentheses. It will also not work if you move the getattr  
to some other place that is not the return statement itself.           
                                                                       
It is intentional that it doesn't work in all cases. Generally it's    
really hard to do even this case (as you can see below). Most people   
will write it like this anyway and the other ones, well they are just  
out of luck I guess :) .
